### ISSUE TITLE
Fresh NextJS App Directory - Builds on Windows - Fails in Cloudflare Build

### ISSUE THREAD

**Issue by RyanGaudion** [cloudflare/next-on-pages#104]
As per #103 I have created a fresh NextJS app and made minor changes.

I can run `npx @cloudflare/next-on-pages --experimental-minify` locally on windows which now works since v0.4.2 release however when building in cloudflare it throws this error:

```
22:12:00.764 | Executing user command: npx @cloudflare/next-on-pages --experimental-minify
-- | --
22:12:00.942 | /opt/buildhome/repo/node_modules/@cloudflare/next-on-pages/dist/index.js:5971
22:12:00.942 | const basePath = routesManifest.basePath ?? "";
22:12:00.942 | ^
22:12:00.942 |  
22:12:00.943 | SyntaxError: Unexpected token '?'
22:12:00.943 | at wrapSafe (internal/modules/cjs/loader.js:1054:16)
22:12:00.943 | at Module._compile (internal/modules/cjs/loader.js:1102:27)
22:12:00.943 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
22:12:00.943 | at Module.load (internal/modules/cjs/loader.js:986:32)
22:12:00.943 | at Function.Module._load (internal/modules/cjs/loader.js:879:14)
22:12:00.943 | at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
22:12:00.943 | at internal/main/run_main_module.js:17:47
22:12:00.953 | Failed: build command exited with code: 1
22:12:02.085 | Failed: an internal error occurred
```

**Comment by RyanGaudion** [comment]
Resolved by setting environment variable of:

`NODE_VERSION` to `14`

**Comment by RyanGaudion** [comment]
This then changed the error to: `experimental.appDir requires Node v16.8.0 or later.`

**Comment by dario-piotrowicz** [comment]
Yeah sorry please try setting `NODE_VERSION` to 16 🙏

**Comment by RyanGaudion** [comment]
@dario-piotrowicz how do I change to use 13.0.0?

**Comment by RyanGaudion** [comment]
Changing to 13.0.0 throws this error:

```
▲ Type error: Layout "src/app/layout.tsx" exports invalid field "metadata". Only "default" and other configuration exports are allowed.
--
```

Trying now without the metadata block

**Comment by RyanGaudion** [comment]
@dario-piotrowicz with metadata removed on 13.0.0 I get the following error:

```

/opt/buildhome/repo/node_modules/@cloudflare/next-on-pages/dist/index.js:5427
--
22:38:00.721 | this[node.value.body.type](node.value.body, state);
22:38:00.721 | ^
22:38:00.722 |  
22:38:00.722 | TypeError: Cannot read property 'type' of undefined
22:38:00.722 | at Object.MethodDefinition (/opt/buildhome/repo/node_modules/@cloudflare/next-on-pages/dist/index.js:5427:26)
22:38:00.722 | at Object.Property (/opt/buildhome/repo/node_modules/@cloudflare/next-on-pages/dist/index.js:5570:12)
22:38:00.723 | at ObjectExpression (/opt/buildhome/repo/node_modules/@cloudflare/next-on-pages/dist/index.js:5536:28)
22:38:00.724 | at Object.ArrayExpression (/opt/buildhome/repo/node_modules/@cloudflare/next-on-pages/dist/index.js:5503:29)
22:38:00.724 | at formatSequence (/opt/buildhome/repo/node_modules/@cloudflare/next-on-pages/dist/index.js:4938:29)
22:38:00.724 | at Object.CallExpression (/opt/buildhome/repo/node_modules/@cloudflare/next-on-pages/dist/index.js:5719:5)
22:38:00.724 | at Object.ExpressionStatement (/opt/buildhome/repo/node_modules/@cloudflare/next-on-pages/dist/index.js:5108:33)
22:38:00.724 | at Object.Program (/opt/buildhome/repo/node_modules/@cloudflare/next-on-pages/dist/index.js:5051:27)
22:38:00.724 | at generate (/opt/buildhome/repo/node_modules/@cloudflare/next-on-pages/dist/index.js:5866:29)
22:38:00.726 | at /opt/buildhome/repo/node_modules/@cloudflare/next-on-pages/dist/index.js:6083:24
22:38:00.746 | Failed: build command exited with code: 1
22:38:01.754 | Failed: an internal error occurred

```

**Comment by dario-piotrowicz** [comment]
if you just switched back to `13.0.0` I suspect that there could be something from latest that doesn't work well with 13? 🤔 

could you please start over and start with:
`npx create-next-app@13.0.0 my-app`
`npm install --save next@13.0.0`

So that you start with the correct 13.0.0 template and pin the next version as well?
(next you can make sure that the runtimes are set to experimental-edge and run npx next-on-pages)

Sorry for the trouble 🙇, please let me know if that works

**Comment by RyanGaudion** [comment]
@dario-piotrowicz also, when will Cloudflare Pages start supporting the latest version of NextJS with App Dir as there are many new features (such as the new metadata API) that I would like to utilise too?

**Comment by dario-piotrowicz** [comment]
Thanks a bunch for trying @RyanGaudion, from your logs it looks like you might be using the wrong npm version
![Screenshot 2023-03-17 at 10 52 02](https://user-images.githubusercontent.com/61631103/225885092-b96c745e-50e5-4900-8369-9da42dd0094a.png)

I think it could be worth it to try the process with the correct node and npm versions, not saying that that is going to fix the issue but it'd be worth a shot I'd imagine.

If that's not the issue I am not sure what it might be, I'll have to investigate it

**Comment by dario-piotrowicz** [comment]
Regarding the latest version, https://github.com/cloudflare/next-on-pages/issues/76 is what blocks us from supporting the latest versions. It shouldn't be that hard to implement honestly, but there are other things we're trying to improve first (as in code quality of the library, better documentation and testing).

I'll try to squeeze that in as well, so I would say soon hopefully 🙂

**Comment by dario-piotrowicz** [comment]
@RyanGaudion you can use the latest version of Next.js now 🙂 

Could you try again with the latest version of both Next.js and next-on-pages and see if things now work for you? 🙂 
(PS: note that you need to set the nodejs compatibility flag)

**Comment by dario-piotrowicz** [comment]
@RyanGaudion could you let me know if this is still an issue? 🙂 🙏
