### ISSUE TITLE
Typescript next projects seem to fail

### ISSUE THREAD

**Issue by joncarlson** [cloudflare/next-on-pages#12]
Followed all the steps in the Documentation, with the exception of passing "--ts" in to the create-next-app command

I've also setup the two flags and NODE_VERSION set to 16

Upon deployment I get a syntax error at the end:

2022-10-26T19:36:53.969765Z	Cloning repository...
2022-10-26T19:36:55.487943Z	Success: Finished cloning repository files
2022-10-26T19:36:56.117328Z	Installing dependencies
2022-10-26T19:36:56.129093Z	Python version set to 2.7
2022-10-26T19:36:59.355548Z	Downloading and installing node v16.18.0...
2022-10-26T19:36:59.7492Z	Downloading https://nodejs.org/dist/v16.18.0/node-v16.18.0-linux-x64.tar.xz...
2022-10-26T19:37:00.267237Z	Computing checksum with sha256sum
2022-10-26T19:37:00.398678Z	Checksums matched!
2022-10-26T19:37:04.815229Z	Now using node v16.18.0 (npm v8.19.2)
2022-10-26T19:37:05.210183Z	Started restoring cached build plugins
2022-10-26T19:37:05.223363Z	Finished restoring cached build plugins
2022-10-26T19:37:05.728749Z	Attempting ruby version 2.7.1, read from environment
2022-10-26T19:37:09.454577Z	Using ruby version 2.7.1
2022-10-26T19:37:09.831197Z	Using PHP version 5.6
2022-10-26T19:37:10.004214Z	5.2 is already installed.
2022-10-26T19:37:10.033486Z	Using Swift version 5.2
2022-10-26T19:37:10.034455Z	Started restoring cached node modules
2022-10-26T19:37:10.053401Z	Finished restoring cached node modules
2022-10-26T19:37:10.576255Z	Installing NPM modules using NPM version 8.19.2
2022-10-26T19:37:10.994932Z	npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
2022-10-26T19:37:10.99531Z	npm WARN config location in the cache, and they are managed by
2022-10-26T19:37:10.995476Z	npm WARN config     [`cacache`](http://npm.im/cacache).
2022-10-26T19:37:11.410054Z	npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
2022-10-26T19:37:11.410518Z	npm WARN config location in the cache, and they are managed by
2022-10-26T19:37:11.410699Z	npm WARN config     [`cacache`](http://npm.im/cacache).
2022-10-26T19:37:22.210057Z	
2022-10-26T19:37:22.210405Z	added 407 packages, and audited 408 packages in 11s
2022-10-26T19:37:22.210883Z	
2022-10-26T19:37:22.211107Z	97 packages are looking for funding
2022-10-26T19:37:22.211328Z	  run `npm fund` for details
2022-10-26T19:37:22.221973Z	
2022-10-26T19:37:22.222291Z	6 moderate severity vulnerabilities
2022-10-26T19:37:22.222436Z	
2022-10-26T19:37:22.222552Z	Some issues need review, and may require choosing
2022-10-26T19:37:22.222687Z	a different dependency.
2022-10-26T19:37:22.222803Z	
2022-10-26T19:37:22.222923Z	Run `npm audit` for details.
2022-10-26T19:37:22.244996Z	NPM modules installed
2022-10-26T19:37:22.838234Z	npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
2022-10-26T19:37:22.838642Z	npm WARN config location in the cache, and they are managed by
2022-10-26T19:37:22.838813Z	npm WARN config     [`cacache`](http://npm.im/cacache).
2022-10-26T19:37:22.857813Z	Installing Hugo 0.54.0
2022-10-26T19:37:23.56131Z	Hugo Static Site Generator v0.54.0-B1A82C61A/extended linux/amd64 BuildDate: 2019-02-01T10:04:38Z
2022-10-26T19:37:23.565706Z	Started restoring cached go cache
2022-10-26T19:37:23.589094Z	Finished restoring cached go cache
2022-10-26T19:37:23.736834Z	go version go1.14.4 linux/amd64
2022-10-26T19:37:23.753772Z	go version go1.14.4 linux/amd64
2022-10-26T19:37:23.757273Z	Installing missing commands
2022-10-26T19:37:23.757612Z	Verify run directory
2022-10-26T19:37:23.757772Z	Executing user command: npx @cloudflare/next-on-pages --experimental-minify
2022-10-26T19:37:24.265282Z	npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
2022-10-26T19:37:24.265616Z	npm WARN config location in the cache, and they are managed by
2022-10-26T19:37:24.265781Z	npm WARN config     [`cacache`](http://npm.im/cacache).
2022-10-26T19:37:24.896506Z	⚡️ @cloudflare/next-to-pages CLI
2022-10-26T19:37:24.901424Z	⚡️
2022-10-26T19:37:24.901752Z	⚡️ Installing 'vercel' CLI...
2022-10-26T19:37:24.901928Z	⚡️
2022-10-26T19:37:25.414383Z	▲ npm
2022-10-26T19:37:25.415235Z	▲  WARN config tmp This setting is no longer used.  npm stores temporary files in a special
2022-10-26T19:37:25.415487Z	▲ npm WARN config location in the cache, and they are managed by
2022-10-26T19:37:25.415629Z	▲ npm WARN config     [`cacache`](http://npm.im/cacache).
2022-10-26T19:37:25.41577Z	▲ 
2022-10-26T19:37:26.40685Z	▲ 
2022-10-26T19:37:26.407293Z	▲ up to date, audited 408 packages in 1s
2022-10-26T19:37:26.407457Z	▲ 
2022-10-26T19:37:26.407576Z	▲ 
2022-10-26T19:37:26.407688Z	▲ 97 packages are looking for funding
2022-10-26T19:37:26.408125Z	▲   run `npm fund` for details
2022-10-26T19:37:26.408287Z	▲ 
2022-10-26T19:37:26.416697Z	▲ 
2022-10-26T19:37:26.41694Z	▲ 6 moderate severity vulnerabilities
2022-10-26T19:37:26.417076Z	▲ 
2022-10-26T19:37:26.417214Z	▲ Some issues need review, and may require choosing
2022-10-26T19:37:26.417384Z	▲ a different dependency.
2022-10-26T19:37:26.417527Z	▲ 
2022-10-26T19:37:26.417659Z	▲ Run `npm audit` for details.
2022-10-26T19:37:26.417773Z	▲ 
2022-10-26T19:37:26.43072Z	⚡️
2022-10-26T19:37:26.431035Z	⚡️
2022-10-26T19:37:26.431223Z	⚡️ Completed 'npx vercel build'.
2022-10-26T19:37:26.431387Z	⚡️
2022-10-26T19:37:26.431532Z	⚡️
2022-10-26T19:37:26.431683Z	⚡️ Building project with 'npx vercel build'...
2022-10-26T19:37:26.431833Z	⚡️
2022-10-26T19:37:26.922421Z	▲ npm
2022-10-26T19:37:26.922816Z	▲  WARN config tmp This setting is no longer used.  npm stores temporary files in a special
2022-10-26T19:37:26.923021Z	▲ npm WARN
2022-10-26T19:37:26.9232Z	▲  config location in the cache, and they are managed by
2022-10-26T19:37:26.923353Z	▲ npm 
2022-10-26T19:37:26.923505Z	▲ WARN config
2022-10-26T19:37:26.923652Z	▲      [`cacache`](http://npm.im/cacache).
2022-10-26T19:37:26.923807Z	▲ 
2022-10-26T19:37:27.689427Z	▲ Vercel CLI 28.4.12
2022-10-26T19:37:27.68996Z	▲ 
2022-10-26T19:37:28.083032Z	▲ Installing dependencies...
2022-10-26T19:37:28.083385Z	▲ 
2022-10-26T19:37:28.501515Z	▲ npm
2022-10-26T19:37:28.501932Z	▲  
2022-10-26T19:37:28.502743Z	▲ WARN config tmp This setting is no longer used.  npm stores temporary files in a special
2022-10-26T19:37:28.502946Z	▲ npm
2022-10-26T19:37:28.503116Z	▲  WARN
2022-10-26T19:37:28.50329Z	▲  config
2022-10-26T19:37:28.503437Z	▲  location in the cache, and they are managed by
2022-10-26T19:37:28.50358Z	▲ npm WARN config
2022-10-26T19:37:28.50371Z	▲      [`cacache`](http://npm.im/cacache).
2022-10-26T19:37:28.50385Z	▲ 
2022-10-26T19:37:29.22338Z	▲ 
2022-10-26T19:37:29.223706Z	▲ up to date in 753ms
2022-10-26T19:37:29.223877Z	▲ 
2022-10-26T19:37:29.224Z	▲ 
2022-10-26T19:37:29.224123Z	▲ 97 packages are looking for funding
2022-10-26T19:37:29.224255Z	▲   run `npm fund` for details
2022-10-26T19:37:29.224369Z	▲ 
2022-10-26T19:37:29.236929Z	▲ Detected Next.js version: 13.0.0
2022-10-26T19:37:29.237337Z	▲ 
2022-10-26T19:37:29.244903Z	▲ Detected `package-lock.json` generated by npm 7+...
2022-10-26T19:37:29.245416Z	▲ 
2022-10-26T19:37:29.245667Z	▲ Running "npm run build"
2022-10-26T19:37:29.246107Z	▲ 
2022-10-26T19:37:29.747487Z	▲ npm
2022-10-26T19:37:29.747918Z	▲  WARN
2022-10-26T19:37:29.748092Z	▲  config tmp This setting is no longer used.  npm stores temporary files in a special
2022-10-26T19:37:29.748243Z	▲ npm WARN
2022-10-26T19:37:29.748667Z	▲  config location in the cache, and they are managed by
2022-10-26T19:37:29.74887Z	▲ npm WARN config     [`cacache`](http://npm.im/cacache).
2022-10-26T19:37:29.749071Z	▲ 
2022-10-26T19:37:29.765875Z	▲ 
2022-10-26T19:37:29.766156Z	▲ > myapp@0.1.0 build
2022-10-26T19:37:29.766312Z	▲ > next build
2022-10-26T19:37:29.766429Z	▲ 
2022-10-26T19:37:29.766538Z	▲ 
2022-10-26T19:37:30.369708Z	▲ warn  - You have enabled experimental feature (runtime) in next.config.js.
2022-10-26T19:37:30.3701Z	▲ 
2022-10-26T19:37:30.370384Z	▲ warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
2022-10-26T19:37:30.37056Z	▲ 
2022-10-26T19:37:30.370715Z	▲ 
2022-10-26T19:37:30.370852Z	▲ 
2022-10-26T19:37:30.418714Z	▲ Attention: Next.js now collects completely anonymous telemetry regarding usage.
2022-10-26T19:37:30.419065Z	▲ 
2022-10-26T19:37:30.419244Z	▲ This information is used to shape Next.js' roadmap and prioritize features.
2022-10-26T19:37:30.419396Z	▲ You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
2022-10-26T19:37:30.41954Z	▲ https://nextjs.org/telemetry
2022-10-26T19:37:30.419677Z	▲ 
2022-10-26T19:37:30.4198Z	▲ 
2022-10-26T19:37:30.55511Z	▲ info  - Linting and checking validity of types...
2022-10-26T19:37:30.555564Z	▲ 
2022-10-26T19:37:32.967327Z	▲ 
2022-10-26T19:37:32.967631Z	▲ ./pages/api/hello.ts
2022-10-26T19:37:32.967803Z	▲ 3:1  Warning: Unexpected default export of anonymous function  import/no-anonymous-default-export
2022-10-26T19:37:32.967956Z	▲ 
2022-10-26T19:37:32.968102Z	▲ info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
2022-10-26T19:37:32.968245Z	▲ info  - Creating an optimized production build...
2022-10-26T19:37:32.968379Z	▲ 
2022-10-26T19:37:33.338757Z	▲ warn  - You are using the experimental Edge Runtime with `experimental.runtime`.
2022-10-26T19:37:33.339151Z	▲ 
2022-10-26T19:37:37.880708Z	▲ info  - Compiled successfully
2022-10-26T19:37:37.881022Z	▲ 
2022-10-26T19:37:37.881196Z	▲ info  - Collecting page data...
2022-10-26T19:37:37.881325Z	▲ 
2022-10-26T19:37:43.138679Z	▲ info  - Generating static pages (0/2)
2022-10-26T19:37:43.139007Z	▲ 
2022-10-26T19:37:43.237084Z	▲ info  - Generating static pages (2/2)
2022-10-26T19:37:43.23791Z	▲ 
2022-10-26T19:37:43.246592Z	▲ info  - Finalizing page optimization...
2022-10-26T19:37:43.246992Z	▲ 
2022-10-26T19:37:43.251362Z	▲ 
2022-10-26T19:37:43.251645Z	▲ 
2022-10-26T19:37:43.273961Z	▲ Route (pages)                              Size     First Load JS
2022-10-26T19:37:43.2744Z	▲ ┌ ℇ /                                      252 B          72.4 kB
2022-10-26T19:37:43.274629Z	▲ ├   /_app                                  0 B            72.1 kB
2022-10-26T19:37:43.274913Z	▲ ├ ○ /404                                   181 B          72.3 kB
2022-10-26T19:37:43.275065Z	▲ └ ℇ /api/hello                              0 B            72.1 kB
2022-10-26T19:37:43.275199Z	▲ + First Load JS shared by all              72.4 kB
2022-10-26T19:37:43.27533Z	▲   ├ chunks/framework-19b86674b25439d7.js   45.4 kB
2022-10-26T19:37:43.275467Z	▲   ├ chunks/main-d2a793b6dc23a82a.js        25.7 kB
2022-10-26T19:37:43.275608Z	▲   ├ chunks/pages/_app-fdaca63b9de4692d.js  295 B
2022-10-26T19:37:43.275739Z	▲   ├ chunks/webpack-8fa1640cc84ba8fe.js     750 B
2022-10-26T19:37:43.275886Z	▲   └ css/ab44ce7add5c3d11.css               247 B
2022-10-26T19:37:43.276009Z	▲ 
2022-10-26T19:37:43.276131Z	▲ 
2022-10-26T19:37:43.276264Z	▲ ℇ  (Streaming)  server-side renders with streaming (uses React 18 SSR streaming or Server Components)
2022-10-26T19:37:43.276384Z	▲ ○  (Static)     automatically rendered as static HTML (uses no initial props)
2022-10-26T19:37:43.276506Z	▲ 
2022-10-26T19:37:43.276614Z	▲ 
2022-10-26T19:37:44.64983Z	▲ Traced Next.js server files in: 1.208s
2022-10-26T19:37:44.650179Z	▲ 
2022-10-26T19:37:45.063343Z	▲ Created all serverless functions in: 413.039ms
2022-10-26T19:37:45.063671Z	▲ 
2022-10-26T19:37:45.174166Z	▲ Collected static files (public/, static/, .next/static): 7.319ms
2022-10-26T19:37:45.174472Z	▲ 
2022-10-26T19:37:45.20914Z	▲ Build Completed in .vercel/output [17s]
2022-10-26T19:37:45.209458Z	▲ 
2022-10-26T19:37:45.277658Z	⚡️
2022-10-26T19:37:45.278206Z	⚡️
2022-10-26T19:37:45.278419Z	⚡️ Completed 'npx vercel build'.
2022-10-26T19:37:45.278559Z	⚡️
2022-10-26T19:37:45.347169Z	/opt/buildhome/repo/node_modules/@cloudflare/next-on-pages/dist/index.js:3057
2022-10-26T19:37:45.347496Z	  var err = new SyntaxError(message);
2022-10-26T19:37:45.347644Z	            ^
2022-10-26T19:37:45.347784Z	
2022-10-26T19:37:45.347928Z	SyntaxError: Unexpected token (200:110)
2022-10-26T19:37:45.348051Z	    at Parser2.pp$4.raise (/opt/buildhome/repo/node_modules/@cloudflare/next-on-pages/dist/index.js:3057:13)
2022-10-26T19:37:45.348168Z	    at Parser2.pp$9.unexpected (/opt/buildhome/repo/node_modules/@cloudflare/next-on-pages/dist/index.js:651:8)
2022-10-26T19:37:45.34831Z	    at Parser2.pp$5.parseExprAtom (/opt/buildhome/repo/node_modules/@cloudflare/next-on-pages/dist/index.js:2440:18)
2022-10-26T19:37:45.348434Z	    at Parser2.pp$5.parseExprSubscripts (/opt/buildhome/repo/node_modules/@cloudflare/next-on-pages/dist/index.js:2304:19)
2022-10-26T19:37:45.348585Z	    at Parser2.pp$5.parseMaybeUnary (/opt/buildhome/repo/node_modules/@cloudflare/next-on-pages/dist/index.js:2275:17)
2022-10-26T19:37:45.3487Z	    at Parser2.pp$5.parseExprOps (/opt/buildhome/repo/node_modules/@cloudflare/next-on-pages/dist/index.js:2206:19)
2022-10-26T19:37:45.348827Z	    at Parser2.pp$5.parseMaybeConditional (/opt/buildhome/repo/node_modules/@cloudflare/next-on-pages/dist/index.js:2190:19)
2022-10-26T19:37:45.348953Z	    at Parser2.pp$5.parseMaybeAssign (/opt/buildhome/repo/node_modules/@cloudflare/next-on-pages/dist/index.js:2147:19)
2022-10-26T19:37:45.349062Z	    at Parser2.pp$5.parseExpression (/opt/buildhome/repo/node_modules/@cloudflare/next-on-pages/dist/index.js:2113:19)
2022-10-26T19:37:45.34917Z	    at Parser2.pp$8.parseStatement (/opt/buildhome/repo/node_modules/@cloudflare/next-on-pages/dist/index.js:839:47) {
2022-10-26T19:37:45.34929Z	  pos: 22596,
2022-10-26T19:37:45.349397Z	  loc: Position2 { line: 200, column: 110 },
2022-10-26T19:37:45.349502Z	  raisedAt: 22597
2022-10-26T19:37:45.349608Z	}
2022-10-26T19:37:45.368882Z	Failed: build command exited with code: 1
2022-10-26T19:37:46.416179Z	Failed: an internal error occurred

**Comment by yvan-eh** [comment]
I'm getting the same error and I'm not using ts

**Comment by kvnang** [comment]
Please see the issue I raised here, as I had the same error, but managed to get it fixed by patching this `@cloudflare/next-on-pages` package:
https://github.com/cloudflare/next-on-pages/issues/8#issuecomment-1290518403

Hope to get this fixed soon!

**Comment by joncarlson** [comment]
Thanks @kvnang ! Confirmed your patch works. Going to close this issue as a duplicate of yours #8
