### ISSUE TITLE
[🐛 Bug]: build error: next.js API Routes can't be created

### ISSUE THREAD

**Issue by jissin** [cloudflare/next-on-pages#164]
### Cli version

0.7.0

### Description

build logs:

```
...

22:49:50.510 | ▲ Collected static files (public/, static/, .next/static): 7.52ms
22:49:50.585 | ▲ Build Completed in .vercel/output [23s]
22:49:54.280 | ⚡️ Building Completed.
22:49:54.495 | (node:1572) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'type' of undefined
22:49:54.495 | at Object.MethodDefinition (/opt/buildhome/.npm/_npx/1525/lib/node_modules/@cloudflare/next-on-pages/dist/index.js:9522:26)
22:49:54.495 | at Object.Property (/opt/buildhome/.npm/_npx/1525/lib/node_modules/@cloudflare/next-on-pages/dist/index.js:9665:12)
22:49:54.495 | at ObjectExpression (/opt/buildhome/.npm/_npx/1525/lib/node_modules/@cloudflare/next-on-pages/dist/index.js:9631:28)
22:49:54.495 | at Object.ArrayExpression (/opt/buildhome/.npm/_npx/1525/lib/node_modules/@cloudflare/next-on-pages/dist/index.js:9598:29)
22:49:54.496 | at formatSequence (/opt/buildhome/.npm/_npx/1525/lib/node_modules/@cloudflare/next-on-pages/dist/index.js:9033:29)
22:49:54.496 | at Object.CallExpression (/opt/buildhome/.npm/_npx/1525/lib/node_modules/@cloudflare/next-on-pages/dist/index.js:9814:5)
22:49:54.496 | at Object.ExpressionStatement (/opt/buildhome/.npm/_npx/1525/lib/node_modules/@cloudflare/next-on-pages/dist/index.js:9203:33)
22:49:54.496 | at Object.Program (/opt/buildhome/.npm/_npx/1525/lib/node_modules/@cloudflare/next-on-pages/dist/index.js:9146:27)
22:49:54.496 | at generate (/opt/buildhome/.npm/_npx/1525/lib/node_modules/@cloudflare/next-on-pages/dist/index.js:9961:29)
22:49:54.496 | at extractWebpackChunks (/opt/buildhome/.npm/_npx/1525/lib/node_modules/@cloudflare/next-on-pages/dist/index.js:10113:30)
22:49:54.496 | (Use `node --trace-warnings ...` to show where the warning was created)
22:49:54.497 | (node:1572) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
22:49:54.497 | (node:1572) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
22:49:54.766 | Finished
22:49:54.766 | Note: No functions dir at /functions found. Skipping.
22:49:54.766 | Validating asset output directory
22:49:55.462 | Deploying your site to Cloudflare's global network...

...

22:49:58.196 | ✨ Success! Uploaded 8 files (23 already uploaded) (1.37 sec)
22:49:58.196 |  
22:49:58.612 | ✨ Upload complete!
22:50:00.301 | Success: Assets published!
22:50:01.252 | Success: Your site was deployed!

...
```

This project was successfully built on March 14, 2023. However, from March 24, 2023 to the present, there have been continuous errors in the logs, indicating that API routes have not been successfully created.

I'm not sure if I provided the full information, if I missed anything, please comment below. Thank you for your work

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment]
Hi @jissin from the logs it look evident that it's breaking why analyzing the js code for the experimental minification, #160 is improving that, could you please try using the PR [prerelease package](https://github.com/cloudflare/next-on-pages/pull/160#issuecomment-1500346428) and see if that solves your issue?

> **Note**
> When running the package please make sure that npm (or whatever package manager you're using) is picking up the correct version, you can do that by checking that the initial message is `@cloudflare/next-on-pages CLI v.0.0.0-xxxxxxx (prerelease for PR #160)`

___

I think it should, please let me know if it doesn't so that we can look into this more (more details or even your source code would really help there)

**Comment by dario-piotrowicz** [comment]
@jissin no problem, I'm glad you solved it :slightly_smiling_face: 

please let me know if there is anything `@cloudflare/next-on-pages` could have done to make it easier to solve
