### ISSUE TITLE
[🐛 Bug]: Failed to generate worker when using Route Handlers with App Router

### ISSUE THREAD

**Issue by rokoucha** [cloudflare/next-on-pages#219]
### next-on-pages environment related information

```
System:
        Platform: linux
        Arch: x64
        Version: #1 SMP PREEMPT_DYNAMIC Wed, 26 Apr 2023 20:50:14 +0000
        CPU: (4) x64 AMD Ryzen 5 PRO 3400GE w/ Radeon Vega Graphics
        Memory: 8 GB
        Shell: /usr/bin/fish
Binaries:
        Node: 19.9.0
        Yarn: N/A
        npm: 9.6.6
        pnpm: N/A
Package Manager Used: npm
Relevant Packages:
        @cloudflare/next-on-pages: 0.10.1
        vercel: 28.20.0
        next: 13.4.0
```

### Description

I tried to use Next.js App Router with Cloudflare Pages Functions and the build failed when using Route Handlers.
No errors occurred on normal pages only.

```
 ❯ npx @cloudflare/next-on-pages
⚡️ @cloudflare/next-on-pages CLI v.0.10.1
⚡️ Detected Package Manager: npm
⚡️ Preparing project...
⚡️ Project is ready
⚡️ Building project...
▲  Vercel CLI 28.20.0
▲  WARNING: You should not upload the `.next` directory.
▲  Installing dependencies...
▲  up to date in 2s
▲
▲  275 packages are looking for funding
▲  run `npm fund` for details
▲  Detected Next.js version: 13.4.0
▲  Detected `package-lock.json` generated by npm 7+...
▲  Running "npm run build"
▲  > build
▲  > next build
▲  warn  - You have enabled experimental feature (typedRoutes) in next.config.js.
▲  warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
▲
▲  info  - Creating an optimized production build...
▲  info  - Compiled successfully
▲  info  - Linting and checking validity of types...
▲  info  - Collecting page data...
▲  info  - Generating static pages (0/3)
▲  info  - Generating static pages (3/3)
▲  info  - Finalizing page optimization...
▲
▲  Route (app)                                Size     First Load JS
▲  ┌ ○ /                                      141 B          76.9 kB
▲  └ ℇ /api                                   0 B                0 B
▲  + First Load JS shared by all              76.8 kB
▲  ├ chunks/139-ab66f6d0e92fcf6c.js         24.4 kB
▲  ├ chunks/2443530c-9d09dde9f906fe30.js    50.5 kB
▲  ├ chunks/main-app-a5aa3221263f4429.js    215 B
▲  └ chunks/webpack-8074fabf81ca3fbd.js     1.61 kB
▲
▲  Route (pages)                              Size     First Load JS
▲  ─ ○ /404                                   178 B            83 kB
▲  + First Load JS shared by all              82.8 kB
▲  ├ chunks/main-b1e0eba8da4ad049.js        81 kB
▲  ├ chunks/pages/_app-c544d6df833bfd4a.js  192 B
▲  └ chunks/webpack-8074fabf81ca3fbd.js     1.61 kB
▲  ℇ  (Streaming)  server-side renders with streaming (uses React 18 SSR streaming or Server Components)
▲  ○  (Static)     automatically rendered as static HTML (uses no initial props)
▲  Traced Next.js server files in: 3.157s
▲  Created all serverless functions in: 2.294s
▲  Collected static files (public/, static/, .next/static): 5.275ms
▲  Build Completed in .vercel/output [18s]
⚡️ Completed `npx vercel build`.
✘ [ERROR] Could not resolve "/wasm/wasm_a7e702bc5ba9227243abda7977c8096f59478d3f.wasm"

    ../../../../../../tmp/xjnkms1k1i/api.func.js:2:64:
      2 │   const wasm_a7e702bc5ba9227243abda7977c8096f59478d3f = require("/wasm/wasm_a7e702bc5ba9227243abda7977c8096f59478d3f.wasm");
        ╵                                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "/wasm/wasm_ef4866ecae192fd87727067cf2c0c0cf9fb8b020.wasm"

    ../../../../../../tmp/xjnkms1k1i/api.func.js:3:62:
      3 │ const wasm_ef4866ecae192fd87727067cf2c0c0cf9fb8b020 = require("/wasm/wasm_ef4866ecae192fd87727067cf2c0c0cf9fb8b020.wasm");
        ╵                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

/home/rokoucha/Projects/github.com/rokoucha/cloudflare-pages-function-next-js/node_modules/esbuild/lib/main.js:1575
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 2 errors:
../../../../../../tmp/xjnkms1k1i/api.func.js:2:64: ERROR: Could not resolve "/wasm/wasm_a7e702bc5ba9227243abda7977c8096f59478d3f.wasm"
../../../../../../tmp/xjnkms1k1i/api.func.js:3:62: ERROR: Could not resolve "/wasm/wasm_ef4866ecae192fd87727067cf2c0c0cf9fb8b020.wasm"
    at failureErrorWithLog (/home/rokoucha/Projects/github.com/rokoucha/cloudflare-pages-function-next-js/node_modules/esbuild/lib/main.js:1575:15)
    at /home/rokoucha/Projects/github.com/rokoucha/cloudflare-pages-function-next-js/node_modules/esbuild/lib/main.js:1033:28
    at runOnEndCallbacks (/home/rokoucha/Projects/github.com/rokoucha/cloudflare-pages-function-next-js/node_modules/esbuild/lib/main.js:1447:61)
    at buildResponseToResult (/home/rokoucha/Projects/github.com/rokoucha/cloudflare-pages-function-next-js/node_modules/esbuild/lib/main.js:1031:7)
    at /home/rokoucha/Projects/github.com/rokoucha/cloudflare-pages-function-next-js/node_modules/esbuild/lib/main.js:1143:14
    at responseCallbacks.<computed> (/home/rokoucha/Projects/github.com/rokoucha/cloudflare-pages-function-next-js/node_modules/esbuild/lib/main.js:680:9)
    at handleIncomingPacket (/home/rokoucha/Projects/github.com/rokoucha/cloudflare-pages-function-next-js/node_modules/esbuild/lib/main.js:735:9)
    at Socket.readFromStdout (/home/rokoucha/Projects/github.com/rokoucha/cloudflare-pages-function-next-js/node_modules/esbuild/lib/main.js:656:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 64,
        file: '../../../../../../tmp/xjnkms1k1i/api.func.js',
        length: 58,
        line: 2,
        lineText: '  const wasm_a7e702bc5ba9227243abda7977c8096f59478d3f = require("/wasm/wasm_a7e702bc5ba9227243abda7977c8096f59478d3f.wasm");',
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'Could not resolve "/wasm/wasm_a7e702bc5ba9227243abda7977c8096f59478d3f.wasm"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 62,
        file: '../../../../../../tmp/xjnkms1k1i/api.func.js',
        length: 58,
        line: 3,
        lineText: 'const wasm_ef4866ecae192fd87727067cf2c0c0cf9fb8b020 = require("/wasm/wasm_ef4866ecae192fd87727067cf2c0c0cf9fb8b020.wasm");',
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'Could not resolve "/wasm/wasm_ef4866ecae192fd87727067cf2c0c0cf9fb8b020.wasm"'
    }
  ],
  warnings: []
}

Node.js v19.9.0
```

### Reproduction

https://github.com/rokoucha/cloudflare-pages-function-next-js

### Pages Deployment Method

None

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment]
Hi @rokoucha thanks a lot for the issue (and especially the reproduction, really appreciated! 😄)

Seems like the problem here is that your app is trying to import `wasm` files which is a known issue: https://github.com/cloudflare/next-on-pages/issues/202

Anyways I pulled down your repo and tried running the app locally, it seems like it worked without issues for me:
![Screenshot 2023-05-05 at 11 14 31](https://user-images.githubusercontent.com/61631103/236432377-61a88f25-64d0-4c07-b8ea-a3d5dd3a4c75.png)

However the app there doesn't contain the `/api` directory which seems likely to be what causes the issue (and I can see the dir in your logs), did you forget to push that?

**Comment by rokoucha** [comment]
@dario-piotrowicz I am so sorry, I just pushed it!

**Comment by dario-piotrowicz** [comment]
no problem it happens 😄👍

**Comment by dario-piotrowicz** [comment]
Seems like importing from `node/server.js` is bringing more things in than necessary (specifically next image code that requires wasm), you can fix this by changing `node/server.js` to `node/server`, and to make typescript understand the import you need to update `moduleResolution` to just `node`:

![Screenshot 2023-05-05 at 12 42 13](https://user-images.githubusercontent.com/61631103/236449173-7ef97914-956c-4c5e-9a54-c0eeb2013bc0.png)

___

I think that `moduleResolution` set to `node` is the default? did you tweak that?

**Comment by dario-piotrowicz** [comment]
yeah I looked at that too but that imports looked very ugly to me 😅 

(out of curiosity, why do you need `node16` there? 🤔)

Anyways if you're ok with it I think we can close the issue since the extra importing is unrelated to next-on-pages and the wasm importing bug is already covered by other issues, would that be ok? 🙂

**Comment by rokoucha** [comment]
> (out of curiosity, why do you need node16 there? 🤔)
That's my hobby 😁

> Anyways if you're ok with it I think we can close the issue since the extra importing is unrelated to next-on-pages and the wasm importing bug is already covered by other issues, would that be ok? 🙂

Yes, it is not next-on-pages bug, I will close this issue.

Thank you for your help! and Thanks for the great software!

**Comment by dario-piotrowicz** [comment]
Awesome! my pleasure 🙂

thank you for using next-on-pages! ❤️
