### ISSUE TITLE
[🐛 Bug]: KV namespace bindings

### ISSUE THREAD

**Issue by willin** [cloudflare/next-on-pages#257]
### next-on-pages environment related information

```
 ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/--version: Not Found - 404

This error happened while installing a direct dependency of /Users/v0/Library/pnpm/store/v3/tmp/dlx-33292

--version is not in the npm registry, or you have no permission to fetch it.

An authorization header was used: Bearer npm_[hidden]

System:
        Platform: darwin
        Arch: arm64
        Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
        CPU: (10) arm64 Apple M1 Max
        Memory: 32 GB
        Shell: /bin/zsh
Binaries:
        Node: 19.1.0
        Yarn: 3.3.0
        npm: 8.19.3
        pnpm: N/A
Package Manager Used: npm
Relevant Packages:
        @cloudflare/next-on-pages: 1.0.0
        vercel: N/A
        next: N/A
```

### Description

```ts
import { KVNamespace } from '@cloudflare/workers-types';
import { NextResponse } from 'next/server';

export async function GET(request: Request) {
  const { DOMAINS } = process.env as any as { DOMAINS: KVNamespace };
  await DOMAINS?.put('test', 'value');

  const data = await DOMAINS?.get('test');
  return NextResponse.json({ data });
}
```

local output: `{}`

pages `Internal Server Error`

```js
{
  "outcome": "ok",
  "scriptName": "pages-worker--1088967-preview",
  "exceptions": [],
  "logs": [
    {
      "message": [
        "Error: internal error"
      ],
      "level": "error",
      "timestamp": 1684379041372
    }
  ],
  "eventTimestamp": 1684379041372,
  "event": {
    "request": {
      "url": "https://domain.js.cool/api/hello/",
      "method": "GET",
      "headers": {
        "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8",
        "accept-encoding": "gzip",
        "accept-language": "zh-CN,zh;q=0.9",
        "cache-control": "max-age=0",
        "cf-connecting-ip": "240e:3ae:937:8ff0:159a:ef6b:7a4a:ae64",
        "cf-connecting-o2o": "1",
        "cf-ipcountry": "CN",
        "cf-ray": "7c90ded08b9c7747",
        "cf-visitor": "{\"scheme\":\"https\"}",
        "connection": "Keep-Alive",
        "cookie": "REDACTED",
        "host": "domain.js.cool",
        "priority": "u=0, i",
        "sec-ch-ua": "\"Brave\";v=\"113\", \"Chromium\";v=\"113\", \"Not-A.Brand\";v=\"24\"",
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"macOS\"",
        "sec-fetch-dest": "document",
        "sec-fetch-mode": "navigate",
        "sec-fetch-site": "same-origin",
        "sec-fetch-user": "?1",
        "sec-gpc": "1",
        "upgrade-insecure-requests": "1",
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
        "x-forwarded-for": "240e:3ae:937:8ff0:159a:ef6b:7a4a:ae64",
        "x-forwarded-proto": "https",
        "x-real-ip": "240e:3ae:937:8ff0:159a:ef6b:7a4a:ae64"
      },
      "cf": {
        "longitude": "118.77380",
        "httpProtocol": "HTTP/3",
        "tlsCipher": "AEAD-AES128-GCM-SHA256",
        "continent": "AS",
        "asn": 4134,
        "clientAcceptEncoding": "gzip",
        "country": "CN",
        "tlsClientAuth": {
          "certIssuerDNLegacy": "",
          "certIssuerSKI": "",
          "certSubjectDNRFC2253": "",
          "certSubjectDNLegacy": "",
          "certFingerprintSHA256": "",
          "certNotBefore": "",
          "certSKI": "",
          "certSerial": "",
          "certIssuerDN": "",
          "certVerified": "NONE",
          "certNotAfter": "",
          "certSubjectDN": "",
          "certPresented": "0",
          "certRevoked": "0",
          "certIssuerSerial": "",
          "certIssuerDNRFC2253": "",
          "certFingerprintSHA1": ""
        },
        "tlsVersion": "TLSv1.3",
        "city": "Nanjing",
        "timezone": "Asia/Shanghai",
        "colo": "LHR",
        "edgeRequestKeepAliveStatus": 1,
        "requestPriority": "",
        "latitude": "32.05890",
        "region": "Jiangsu",
        "regionCode": "JS",
        "asOrganization": "China Telecom",
        "pagesHostName": "dev.free-domain.pages.dev",
        "botManagement": {
          "corporateProxy": false,
          "verifiedBot": false,
          "ja3Hash": "25b4882c2bcb50cd6b469ff28c596742",
          "jsDetection": {
            "passed": false
          },
          "staticResource": false,
          "detectionIds": {},
          "score": 99
        }
      }
    },
    "response": {
      "status": 404
    }
  },
  "id": 13
}
```

### Reproduction

https://github.com/willin/domain/tree/dev

https://github.com/willin/domain/commit/77f0996f09c705c0981d9d62c159710c8a6b9db7

### Pages Deployment Method

None

### Pages Deployment ID

d5eedecb-1159-4158-af5b-ac753101dfb7

### Additional Information

```bash
npx wrangler@3 pages dev .vercel/output/static --kv=DOMAINS --compatibility-flag=nodejs_compat
```

### Would you like to help?

- [X] Would you like to help fixing this bug?

**Comment by james-elicx** [comment]
Hello, sorry to hear that you're experiencing issues with bindings ☹️

I've just deployed a clone of your dev branch. I noticed a small issue with the `trailingSlash` option in your `next.config.js` that results in `/api/hello/` returning not found. Please try removing that setting for the moment. I'm going to look into that problem separately.

Please also opt the `/api/hello` page into the edge runtime by exporting the following from it:
```ts
export const runtime = 'edge';
```

Anyway, onto the issue at hand. I wasn't able to reproduce the issue locally with the wrangler command that you wrote above. I also wasn't able to reproduce the issue on a deployment to Pages either.

Please ensure that you have added your binding in your Pages project's settings page - that may be why you are receiving `{}`.

Deployment: https://f93b4910.nop-issue-257-repro.pages.dev/api/hello

Binding Setting:

![image](https://github.com/cloudflare/next-on-pages/assets/10815538/d80fd7c5-b0db-47ae-854f-dd0531ecf633)

Could you try the following steps and let me know if you still have problems:
1. Remove the `trailingSlash` option in `next.config.js`.
2. Opt the `/api/hello` page into the edge runtime.
3. Check that you add the binding in your Pages project settings (Settings -> Functions -> KV Namespace Bindings).

**Comment by willin** [comment]
```ts
const nextConfig = {
  reactStrictMode: true,
  runtime: 'edge'
};
```

runtime `edge` already in the next config

**Comment by james-elicx** [comment]
> ```ts
> const nextConfig = {
>   reactStrictMode: true,
>   runtime: 'edge'
> };
> ```
> 
> runtime `edge` already in the next config

That option is no longer supported by Next.js.

**Comment by willin** [comment]
done. thx.

**Comment by willin** [comment]
besides, i'm using `build` & `dev` every time.

when i use `watch`, it's always restarting all the time.

**Comment by james-elicx** [comment]
> ```shell
> npm run build && npx wrangler@3 pages dev .vercel/output/static --kv=DOMAINS --compatibility-flag=nodejs_compat --compatibility-date=2023-05-12
> ```
> 
> but however i cannot debug locally any more...

The `npm run build` command builds Next.js but does not run `npx @cloudflare/next-on-pages`. You could try doing `npm run pages:build` instead.

**Comment by willin** [comment]
oh,sorry.

```bash
npm run pages:build && npx wrangler@3 pages dev .vercel/output/static --kv=DOMAINS --compatibility-flag=nodejs_compat --compatibility-date=2023-05-12
```

```
To run an edge preview session for your Worker, use wrangler dev --remote
Your worker has access to the following bindings:
- KV Namespaces:
  - DOMAINS: DOMAINS
⎔ Starting local server...
▲ [WARNING] Parsed 1 valid header rule.


*** Fatal uncaught kj::Exception: kj/async-io-unix.c++:945: failed: ::bind(sockfd, &addr.generic, addrlen): Address already in use; toString() = 0.0.0.0:8788
stack: 1038cae4f 1038cabe7 1038c847f 1021dce03 1021dd6cc 1021a8927 1021ac333 1021ac167 1021ac14f 1038fec8b 1038feee7 1038fd62f 1038fd3ff 1021a01ab 191f8ff27
✘ [ERROR] MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
```

--- 

`npm run pages:watch`:

<img width="879" alt="image" src="https://github.com/cloudflare/next-on-pages/assets/1890238/6d34421c-f3e8-4987-af19-b7949d0365a6">

**Comment by james-elicx** [comment]
> oh,sorry.
> 
> ```shell
> npm run pages:build && npx wrangler@3 pages dev .vercel/output/static --kv=DOMAINS --compatibility-flag=nodejs_compat --compatibility-date=2023-05-12
> ```
> 
> ```
> To run an edge preview session for your Worker, use wrangler dev --remote
> Your worker has access to the following bindings:
> - KV Namespaces:
>   - DOMAINS: DOMAINS
> ⎔ Starting local server...
> ▲ [WARNING] Parsed 1 valid header rule.
> 
> 
> *** Fatal uncaught kj::Exception: kj/async-io-unix.c++:945: failed: ::bind(sockfd, &addr.generic, addrlen): Address already in use; toString() = 0.0.0.0:8788
> stack: 1038cae4f 1038cabe7 1038c847f 1021dce03 1021dd6cc 1021a8927 1021ac333 1021ac167 1021ac14f 1038fec8b 1038feee7 1038fd62f 1038fd3ff 1021a01ab 191f8ff27
> ✘ [ERROR] MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.

I can see the error says `Address already in use`. I would imagine this means that you are already running an instance. Can you please check if you are already running wrangler? You should only be running instance `wrangler pages dev`

**Comment by willin** [comment]
```
Error: KV PUT failed: 500 Internal Server Error {
  stack: Error: KV PUT failed: 500 Internal Server Error,
  message: KV PUT failed: 500 Internal Server Error
}
[mf:inf] GET /api/hello 500 Internal Server Error (41ms)
[mf:inf] GET /favicon.ico 200 OK (11ms)
[mf:err] Error: Could not locate the bindings file. Tried:
 → /Users/v0/.npm/_npx/0eedb5afd4158ff3/node_modules/better-sqlite3/build/better_sqlite3.node
 → /Users/v0/.npm/_npx/0eedb5afd4158ff3/node_modules/better-sqlite3/build/Debug/better_sqlite3.node
 → /Users/v0/.npm/_npx/0eedb5afd4158ff3/node_modules/better-sqlite3/build/Release/better_sqlite3.node
 → /Users/v0/.npm/_npx/0eedb5afd4158ff3/node_modules/better-sqlite3/out/Debug/better_sqlite3.node
 → /Users/v0/.npm/_npx/0eedb5afd4158ff3/node_modules/better-sqlite3/Debug/better_sqlite3.node
 → /Users/v0/.npm/_npx/0eedb5afd4158ff3/node_modules/better-sqlite3/out/Release/better_sqlite3.node
 → /Users/v0/.npm/_npx/0eedb5afd4158ff3/node_modules/better-sqlite3/Release/better_sqlite3.node
 → /Users/v0/.npm/_npx/0eedb5afd4158ff3/node_modules/better-sqlite3/build/default/better_sqlite3.node
 → /Users/v0/.npm/_npx/0eedb5afd4158ff3/node_modules/better-sqlite3/compiled/19.1.0/darwin/arm64/better_sqlite3.node
 → /Users/v0/.npm/_npx/0eedb5afd4158ff3/node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node
 → /Users/v0/.npm/_npx/0eedb5afd4158ff3/node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node
 → /Users/v0/.npm/_npx/0eedb5afd4158ff3/node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node
 → /Users/v0/.npm/_npx/0eedb5afd4158ff3/node_modules/better-sqlite3/lib/binding/node-v111-darwin-arm64/better_sqlite3.node
    at bindings (/Users/v0/.npm/_npx/0eedb5afd4158ff3/node_modules/bindings/bindings.js:126:9)
    at new Database (/Users/v0/.npm/_npx/0eedb5afd4158ff3/node_modules/better-sqlite3/lib/database.js:48:64)
    at createFileStorage (/Users/v0/.npm/_npx/0eedb5afd4158ff3/node_modules/miniflare/dist/src/index.js:3627:14)
    at GatewayFactory.getStorage (/Users/v0/.npm/_npx/0eedb5afd4158ff3/node_modules/miniflare/dist/src/index.js:3686:12)
    at GatewayFactory.get (/Users/v0/.npm/_npx/0eedb5afd4158ff3/node_modules/miniflare/dist/src/index.js:3692:26)
    at KVRouter.put (/Users/v0/.npm/_npx/0eedb5afd4158ff3/node_modules/miniflare/dist/src/index.js:4425:41)
    at KVRouter.route (/Users/v0/.npm/_npx/0eedb5afd4158ff3/node_modules/miniflare/dist/src/index.js:3822:27)
    at #handleLoopbackPlugins (/Users/v0/.npm/_npx/0eedb5afd4158ff3/node_modules/miniflare/dist/src/index.js:8919:54)
    at #handleLoopback (/Users/v0/.npm/_npx/0eedb5afd4158ff3/node_modules/miniflare/dist/src/index.js:8988:53)
    at Server.emit (node:events:525:35)
[mf:inf] GET /api/hello 500 Internal Server Error (15ms)
Error: KV PUT failed: 500 Internal Server Error {
  stack: Error: KV PUT failed: 500 Internal Server Error,
  message: KV PUT failed: 500 Internal Server Error
}
```

**Comment by willin** [comment]
<img width="1208" alt="image" src="https://github.com/cloudflare/next-on-pages/assets/1890238/b398adc8-c2b7-4467-894d-e9a2c1cdc328">
