### ISSUE TITLE
Error when running npx @cloudflare/next-on-pages for next13

### ISSUE THREAD

**Issue by jeremyrajan** [cloudflare/next-on-pages#26]
Hello,

I am trying to build with latest version of next13 but getting the following error.

```
22:50:45.402 | Executing user command: npx @cloudflare/next-on-pages
-- | --
22:50:45.547 | /opt/buildhome/repo/node_modules/@cloudflare/next-on-pages/dist/index.js:6013
22:50:45.547 | ({ type, expression }) => type === "ExpressionStatement" && expression?.type === "CallExpression" && expression.callee?.type === "MemberExpression" && expression.callee.object?.type === "AssignmentExpression" && expression.callee.object.left?.object?.name === "self" && expression.callee.object.left.property?.value === "webpackChunk_N_E" && expression.arguments?.[0]?.elements?.[1]?.type === "ObjectExpression"
22:50:45.548 | ^
22:50:45.548 |  
22:50:45.548 | SyntaxError: Unexpected token '.'
22:50:45.548 | at wrapSafe (internal/modules/cjs/loader.js:1054:16)
22:50:45.548 | at Module._compile (internal/modules/cjs/loader.js:1102:27)
22:50:45.548 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
22:50:45.548 | at Module.load (internal/modules/cjs/loader.js:986:32)
22:50:45.549 | at Function.Module._load (internal/modules/cjs/loader.js:879:14)
22:50:45.549 | at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
22:50:45.549 | at internal/main/run_main_module.js:17:47
22:50:45.556 | Failed: build command exited with code: 1
22:50:46.611 | Failed: an internal error occurred
```
Its a typescript app and I have followed all the instructions.

Thanks,
Jeremy

**Comment by w00fz** [comment]
I ran into this myself and most likely you haven't properly set the `NODE_VERSION` environmental variable as suggested (or you mistyped like I did 🙃).

I originally set to `18` thinking that would be enough but prefixes are not supported apparently, so you have to be specific. I ended up setting both Production and Preview to  `NODE_VERSION` => `16.18.1`.

You can change these from the Settings -> Environmental variables of your Page app.

**Comment by GregBrimble** [comment]
@w00fz is probably correct. Please make sure you're using a modern `NODE_VERSION` environment variable.
