### ISSUE TITLE
[🐛 Bug]: local development fails with error message

### ISSUE THREAD

**Issue by dberhane** [cloudflare/next-on-pages#269]
### next-on-pages environment related information

System:
	Platform: linux
	Arch: x64
	Version: #55-Ubuntu SMP Mon Aug 8 14:58:10 UTC 2022
	CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
	Memory: 15 GB
	Shell: /bin/bash
Binaries:
	Node: 18.15.0
	Yarn: 1.22.19
	npm: 9.5.0
	pnpm: N/A
Package Manager Used: npm
Relevant Packages:
	@cloudflare/next-on-pages: 0.10.1
	vercel: N/A
	next: N/A

### Description

I followed the README installation guideline and the Next.js Cloudflare Pages local development CLI does not work for me. When I run the local development CLI locally:

npx @cloudflare/next-on-pages`

I always get the following error message:
```
▲  Build Completed in .vercel/output [22s]
⚡️ Completed `npx vercel build`.
✘ [ERROR] Could not resolve "/wasm/wasm_ef4866ecae192fd87727067cf2c0c0cf9fb8b020.wasm"

    ../../../../../tmp/jvi86xkj1r/favicon.ico.func.js:2:64:
      2 │   const wasm_ef4866ecae192fd87727067cf2c0c0cf9fb8b020 = require("/wasm/wasm_ef4866ecae192fd87727067cf2c0c0cf9fb8b020.wasm");
        ╵                                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "/wasm/wasm_a7e702bc5ba9227243abda7977c8096f59478d3f.wasm"

    ../../../../../tmp/jvi86xkj1r/favicon.ico.func.js:3:62:
      3 │ const wasm_a7e702bc5ba9227243abda7977c8096f59478d3f = require("/wasm/wasm_a7e702bc5ba9227243abda7977c8096f59478d3f.wasm");
        ╵                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

/home/dberhane/projects/cloudflare/next-cloudflare/node_modules/esbuild/lib/main.js:1575
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 2 errors:
../../../../../tmp/jvi86xkj1r/favicon.ico.func.js:2:64: ERROR: Could not resolve "/wasm/wasm_ef4866ecae192fd87727067cf2c0c0cf9fb8b020.wasm"
../../../../../tmp/jvi86xkj1r/favicon.ico.func.js:3:62: ERROR: Could not resolve "/wasm/wasm_a7e702bc5ba9227243abda7977c8096f59478d3f.wasm"
    at failureErrorWithLog (/home/dberhane/projects/cloudflare/next-cloudflare/node_modules/esbuild/lib/main.js:1575:15)
    at /home/dberhane/projects/cloudflare/next-cloudflare/node_modules/esbuild/lib/main.js:1033:28
    at runOnEndCallbacks (/home/dberhane/projects/cloudflare/next-cloudflare/node_modules/esbuild/lib/main.js:1447:61)
    at buildResponseToResult (/home/dberhane/projects/cloudflare/next-cloudflare/node_modules/esbuild/lib/main.js:1031:7)
    at /home/dberhane/projects/cloudflare/next-cloudflare/node_modules/esbuild/lib/main.js:1143:14
    at responseCallbacks.<computed> (/home/dberhane/projects/cloudflare/next-cloudflare/node_modules/esbuild/lib/main.js:680:9)
    at handleIncomingPacket (/home/dberhane/projects/cloudflare/next-cloudflare/node_modules/esbuild/lib/main.js:735:9)
    at Socket.readFromStdout (/home/dberhane/projects/cloudflare/next-cloudflare/node_modules/esbuild/lib/main.js:656:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 64,
        file: '../../../../../tmp/jvi86xkj1r/favicon.ico.func.js',
        length: 58,
        line: 2,
        lineText: '  const wasm_ef4866ecae192fd87727067cf2c0c0cf9fb8b020 = require("/wasm/wasm_ef4866ecae192fd87727067cf2c0c0cf9fb8b020.wasm");',
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'Could not resolve "/wasm/wasm_ef4866ecae192fd87727067cf2c0c0cf9fb8b020.wasm"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 62,
        file: '../../../../../tmp/jvi86xkj1r/favicon.ico.func.js',
        length: 58,
        line: 3,
        lineText: 'const wasm_a7e702bc5ba9227243abda7977c8096f59478d3f = require("/wasm/wasm_a7e702bc5ba9227243abda7977c8096f59478d3f.wasm");',
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'Could not resolve "/wasm/wasm_a7e702bc5ba9227243abda7977c8096f59478d3f.wasm"'
    }
  ],
  warnings: []
}

Node.js v18.15.0
```

### Reproduction

I have just followed carefully your step-by-step Quick Start guidelines. The standard Next.js npm commands for Vercel work fine:

```
npm run dev
npm run build
npm run start
```

The local development CLI for Next on Pages does not work and fails with the error message:
[ERROR] Could not resolve "/wasm/wasm_ef4866ecae192fd87727067cf2c0c0cf9fb8b020.wasm"

### Pages Deployment Method

None

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment]
Hi @dberhane, it seems like your issue is that you can't import `wasm` modules

the fix has already been introduced in https://github.com/cloudflare/next-on-pages/pull/256 but only recently so it's not yet in the stable release (also you are using `0.10.1` please use `1.0.0` instead 🙏 (by installing it as a dependency or by running `npx @cloudflare/next-on-pages@1`) )

The fix should land soon, but in the meantime you can try the beta canary release, wasm importing should work fine there: `npx @cloudflare/next-on-pages@beta` 🙂

Please have a look and let me know if everything works fine with that 🙏

**Comment by dberhane** [comment]
Using `@cloudflare/next-on-pages@beta` comes up with a different error message:

```
▲  Done in 24.97s.
⚡️ Completed `yarn vercel build`.
/home/dberhane/.npm/_npx/be5105308c27b00d/node_modules/@cloudflare/next-on-pages/dist/index.js:10504
  var err = new SyntaxError(message);
            ^

SyntaxError: Unexpected token (3:10)
    at pp$4.raise (/home/dberhane/.npm/_npx/be5105308c27b00d/node_modules/@cloudflare/next-on-pages/dist/index.js:10504:13)
    at pp$9.unexpected (/home/dberhane/.npm/_npx/be5105308c27b00d/node_modules/@cloudflare/next-on-pages/dist/index.js:8098:8)
    at pp$9.semicolon (/home/dberhane/.npm/_npx/be5105308c27b00d/node_modules/@cloudflare/next-on-pages/dist/index.js:8080:10)
    at pp$8.parseExpressionStatement (/home/dberhane/.npm/_npx/be5105308c27b00d/node_modules/@cloudflare/next-on-pages/dist/index.js:8561:8)
    at pp$8.parseStatement (/home/dberhane/.npm/_npx/be5105308c27b00d/node_modules/@cloudflare/next-on-pages/dist/index.js:8290:21)
    at pp$8.parseTopLevel (/home/dberhane/.npm/_npx/be5105308c27b00d/node_modules/@cloudflare/next-on-pages/dist/index.js:8152:21)
    at Parser2.parse (/home/dberhane/.npm/_npx/be5105308c27b00d/node_modules/@cloudflare/next-on-pages/dist/index.js:7951:15)
    at Function.parse2 [as parse] (/home/dberhane/.npm/_npx/be5105308c27b00d/node_modules/@cloudflare/next-on-pages/dist/index.js:8006:35)
    at parse3 (/home/dberhane/.npm/_npx/be5105308c27b00d/node_modules/@cloudflare/next-on-pages/dist/index.js:12313:17)
    at extractWebpackChunks (/home/dberhane/.npm/_npx/be5105308c27b00d/node_modules/@cloudflare/next-on-pages/dist/index.js:12631:26) {
  pos: 133,
  loc: Position2 { line: 3, column: 10 },
  raisedAt: 178
}

Node.js v18.15.0
```

**Comment by dario-piotrowicz** [comment]
I see, that does seem to be a different bug... sorry about that 😓 

I'll look into it 🙇

(PS: I am not sure if possible, but if you could share your code that would be very very useful to debug/solve this 🙏 )

**Comment by dberhane** [comment]
Thank you @dario-piotrowicz for your efforts. The next.js app is the starter app described in your README and here is the GitHub repo for it:
https://github.com/dberhane/next-cloudflare

**Comment by dario-piotrowicz** [comment]
No problem @dberhane, sorry you kept getting errors

The last one was a silly bug I recently introduced, https://github.com/cloudflare/next-on-pages/pull/272 should fix it 🙂 

I did try this on your reproduction and it seems like it fixes the issue and the app runs as expected locally
(PS: thank you so very much for the repro, it is always such a big help! 🙏)

Please try the [prerelease package](https://github.com/cloudflare/next-on-pages/pull/272#issuecomment-1558867816) to see if now everything works fine for you 😄

**Comment by dario-piotrowicz** [comment]
@dberhane just merged the PR, so the change should be in the [latest beta package](https://www.npmjs.com/package/@cloudflare/next-on-pages/v/0.0.0-e4a3ee4) 🙂
