### ISSUE TITLE
[🐛 Bug]: 500 Internal Server Error in dynamic route

### ISSUE THREAD

**Issue by TeramachiShunsuke** [cloudflare/next-on-pages#290]
### next-on-pages environment related information

System:
        Platform: darwin
        Arch: arm64
        Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
        CPU: (8) arm64 Apple M1 Pro
        Memory: 32 GB
        Shell: /opt/homebrew/bin/fish
Binaries:
        Node: 16.20.0
        Yarn: 1.22.19
        npm: 8.19.4
        pnpm: N/A
Package Manager Used: yarn (classic)
Relevant Packages:
        @cloudflare/next-on-pages: 1.0.1
        vercel: N/A
        next: N/A

### Description

I am getting an Internal Server Error when I try to use AppRouter for dynamic routing.

The error log is as follows

`TypeError: Cannot read properties of undefined (reading 'project_id')
    at oe (__next-on-pages-dist__/chunks/4794.js:31:6564)
    at U (__next-on-pages-dist__/chunks/4794.js:31:12177)
    at __next-on-pages-dist__/chunks/4794.js:31:12975
    at Array.map (<anonymous>)
    at U (__next-on-pages-dist__/chunks/4794.js:31:12915)
    at be (__next-on-pages-dist__/chunks/4794.js:31:13363)
    at de (__next-on-pages-dist__/chunks/4794.js:31:13949)
    at __next-on-pages-dist__/chunks/4794.js:31:18492
    at Object.wrap (__next-on-pages-dist__/chunks/4794.js:26:53733)
    at __next-on-pages-dist__/chunks/4794.js:31:18454 {
  stack: TypeError: Cannot read properties of undefined (re…at __next-on-pages-dist__/chunks/4794.js:31:18454,
  message: Cannot read properties of undefined (reading 'project_id')
}
TypeError: Cannot read properties of null (reading 'default')
    at Object.loadComponent (__next-on-pages-dist__/chunks/4794.js:26:23194)
    at Ts.findPageComponents (__next-on-pages-dist__/chunks/4794.js:26:20169)
    at Ts.renderErrorToResponseImpl (__next-on-pages-dist__/chunks/4794.js:13:6737)
    at async Ts.renderToResponseImpl (__next-on-pages-dist__/chunks/4794.js:13:4967)
    at async Ts.pipeImpl (__next-on-pages-dist__/chunks/4794.js:11:9398)
    at async Object.fn (__next-on-pages-dist__/chunks/4794.js:26:18709)
    at async Mi.execute (__next-on-pages-dist__/chunks/4794.js:10:16447)
    at async Ts.runImpl (__next-on-pages-dist__/chunks/4794.js:11:8992) {
  stack: TypeError: Cannot read properties of null (reading…l (__next-on-pages-dist__/chunks/4794.js:11:8992),
  message: Cannot read properties of null (reading 'default')
}
TypeError: Cannot read properties of undefined (reading 'project_id')
    at oe (__next-on-pages-dist__/chunks/4794.js:31:6564)
    at __next-on-pages-dist__/chunks/4794.js:31:10293
    at Array.map (<anonymous>)
    at ge (__next-on-pages-dist__/chunks/4794.js:31:10234)
    at async Gs.transformStream (__next-on-pages-dist__/chunks/4794.js:31:14237) {
  stack: TypeError: Cannot read properties of undefined (re… (__next-on-pages-dist__/chunks/4794.js:31:14237),
  message: Cannot read properties of undefined (reading 'project_id')
}
Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error. {
  digest: 1300469089,
  stack: Error: An error occurred in the Server Components …additional details about the nature of the error.,
  message: An error occurred in the Server Components render.…additional details about the nature of the error.
}`

The following commands are being executed
`
npx @cloudflare/next-on-pages
npx wrangler pages dev .vercel/output/static --compatibility-flag=nodejs_compat --local
`

The versions of the package are as follows
`
    "@cloudflare/next-on-pages": "^1.0.1",
    "next-on-pages-vercel-cli": "^29.3.0-next-on-pages-fix-3",
    "wrangler": "^3.0.1"`

![image](https://github.com/cloudflare/next-on-pages/assets/57646130/a6637555-2475-43e4-a383-4901d1e87103)

### Pages Deployment Method

Direct Upload (`wrangler pages publish` or the @cloudflare/pages-action GitHub Action)

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by james-elicx** [comment]
Hello, sorry to hear you're having problems. 🙁

It sounds like there might be an error in the code on your page. Would you be able to share the code for the route, or a reproduction, so that we can try and help?

**Comment by TeramachiShunsuke** [comment]
Hello!

Thanks for the quick reply.
Which code do you need?
Is it in the captcha?
All codes may be difficult to follow, but we will publish as much as possible.

![image](https://github.com/cloudflare/next-on-pages/assets/57646130/097b4f74-e231-42ff-a6cb-7a75aa620b8f)

**Comment by james-elicx** [comment]
> Thanks for the quick reply. Which code do you need? Is it in the captcha? All codes may be difficult to follow, but we will publish as much as possible.
> 

Ideally, a link to a repository for a reproduction of the problem, or the code where you are referencing `project_id`.

**Comment by james-elicx** [comment]
> Sorry, the repository cannot be made public. However, you can publish a part of tsx that uses project_id. I believe that this code is getting the project_id as a Page.
> 
> ` const ProjectPage = async ({ params }: { params: { project_id: string } }) => { const projects: Project[] = [] const project_id = params.project_id // Some business logic　... }
> 
> export default ProjectPage export const runtime = 'edge' `

I'm afraid I'm not getting much luck trying to reproduce the problem with the code you have shared 🙁

Since you aren't able to share the current repository, perhaps you could try and make a new project that has a similar setup and encounters the same problem?

**Comment by TeramachiShunsuke** [comment]
This is my guess,
Is it because of this description of middleware?
I asked this question because of the description that dynamic routing uses headers.
And if so, do you know how to resolve this?

`import { NextResponse } from 'next/server'
import { NextRequest } from 'next/server'
import { isAuthenticated } from '@/lib/auth'

export async function middleware(request: NextRequest) {
    const pathname = request.nextUrl.pathname
    const isSigned = await isAuthenticated(request)
    if (pathname.startsWith('/_next')) {
        return NextResponse.next()
    }
    if (!isSigned) {
        if (pathname !== '/signin') {
            request.nextUrl.pathname = '/signin'
            return NextResponse.redirect(request.nextUrl)
        }
    } else {
        if (pathname.startsWith('/signin')) {
            request.nextUrl.pathname = '/'
            return NextResponse.redirect(request.nextUrl)
        } else {
            return NextResponse.next()
        }
    }
}
`

**Comment by TeramachiShunsuke** [comment]
Add information to ```http://localhost:port/[project_id]
```
and can be accessed by accessing
It seems that the directory [project_id] is determined to be a static routing!

**Comment by james-elicx** [comment]
I have tried adding your middleware to my local project for this issue and I am still not able to reproduce the problem.

Please try and create another repo that has the same issue that you are able to share so that we can assist you.

**Comment by TeramachiShunsuke** [comment]
[repo](https://github.com/TeramachiShunsuke/Nextjs-Cloudflare)
I have confirmed that this repository also has the same problem.
Is there something wrong with the way I made it?
Yes, it is true that you can create a Nextjs project and
I can confirm that adding a simple Page.tsx will not cause any problems.
Is there something interfering with my installation of Package?

**Comment by james-elicx** [comment]
> Thanks for the PR.
> The correction has been confirmed.
> Should I keep this issue Open until the PR is merged?
> 
> By the way, how soon will this PR be released?

It will be automatically closed once the PR is merged, which will hopefully be rather soon.

**Comment by TeramachiShunsuke** [comment]
Thank you again.
If so, this issue is closed.
