### ISSUE TITLE
Next.js TypeError: Cannot read properties of undefined (reading 'files')

### ISSUE THREAD

**Issue by marcello-palmitessa** [cloudflare/next-on-pages#66]
Hi, trying to build a Next.js project, using React 18, Next.js v13 and the pages folder, after applying all the changes by the guide ([](https://developers.cloudflare.com/pages/framework-guides/deploy-a-nextjs-site/)) setting the Edge API Routes and the Edge Runtime also for the pages, I get the following error:

```
14:05:40.491 | ▲ info  - Collecting page data...
-- | --
14:05:40.492 | ▲
14:05:41.533 | ▲ TypeError: Cannot read properties of undefined (reading 'files')
14:05:41.534 | ▲     at /opt/buildhome/repo/node_modules/next/dist/build/utils.js:817:33
14:05:41.534 | ▲     at Span.traceAsyncFn (/opt/buildhome/repo/node_modules/next/dist/trace/trace.js:79:26)
14:05:41.534 | ▲     at Object.isPageStatic (/opt/buildhome/repo/node_modules/next/dist/build/utils.js:802:29)
14:05:41.534 | ▲     at execFunction (/opt/buildhome/repo/node_modules/next/dist/compiled/jest-worker/processChild.js:1:2828)
14:05:41.534 | ▲     at execHelper (/opt/buildhome/repo/node_modules/next/dist/compiled/jest-worker/processChild.js:1:2486)
14:05:41.535 | ▲     at execMethod (/opt/buildhome/repo/node_modules/next/dist/compiled/jest-worker/processChild.js:1:2574)
14:05:41.535 | ▲     at process.messageListener (/opt/buildhome/repo/node_modules/next/dist/compiled/jest-worker/processChild.js:1:1284)
14:05:41.535 | ▲     at process.emit (node:events:390:28)
14:05:41.535 | ▲     at emit (node:internal/child_process:917:12)
14:05:41.535 | ▲     at processTicksAndRejections (node:internal/process/task_queues:84:21)
14:05:41.536 | ▲
14:05:41.539 | ▲
14:05:41.539 | ▲ > Build error occurred
14:05:41.539 | ▲
14:05:41.541 | ▲ Error: Failed to collect page data for /500
14:05:41.541 | ▲     at /opt/buildhome/repo/node_modules/next/dist/build/utils.js:963:15
14:05:41.541 | ▲     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
14:05:41.541 | ▲   type: 'Error'
14:05:41.542 | ▲ }
14:05:41.542 | ▲
14:05:41.623 | ▲ Error: Command "npm run build" exited with 1
```

My next.config.js:
```
const path = require('path');
const withBundleAnalyzer = require('@next/bundle-analyzer')({
  enabled: process.env.ANALYZE === 'true'
});

module.exports = withBundleAnalyzer({
  experimental: {
    legacyBrowsers: false,
    newNextLinkBehavior: true,
    fallbackNodePolyfills: false,
    nextScriptWorkers: true
  },
  swcMinify: true,
  reactStrictMode: false, // disabled to allow gsap to properly run in dev mode
  trailingSlash: true,
  i18n: {
    locales: ['en'],
    defaultLocale: 'en',
    localeDetection: true
  },
  sassOptions: {
    includePaths: [path.join(__dirname, 'styles')]
  }
});
```

Any ideas please ?

**Comment by marcello-palmitessa** [comment]
Someone else have this issue with next.js ?

**Comment by HMilbradt** [comment]
I'm getting the same issue.  Same versions as you as well

**Comment by ahmed-alamodi** [comment]
yes, I'm getting the same

**Comment by james-elicx** [comment]
This is a Next.js issue, not a next-on-pages one. https://github.com/vercel/next.js/issues/40379

Although not ideal, the workaround of removing 404 and 500 pages may resolve it for you.

**Comment by dario-piotrowicz** [comment]
Closing this issue since it doesn't look next-on-pages related as @james-elicx mentioned.
