### ISSUE TITLE
[🐛 Bug]: Project ID is needed

### ISSUE THREAD

**Issue by Oni-giri** [cloudflare/next-on-pages#691]
### next-on-pages environment related information

01:16:49.972 | Executing user command: npx @cloudflare/next-on-pages@1
-- | --
01:16:51.601 | ⚡️ @cloudflare/next-on-pages CLI v.1.10.0
01:16:51.978 | ⚡️ Detected Package Manager: npm (9.6.7)
01:16:51.979 | ⚡️ Preparing project...
01:16:51.981 | ⚡️ Project is ready
01:16:51.981 | ⚡️ Building project...
01:16:53.039 | ▲  Vercel CLI 33.5.3
01:16:53.377 | ▲  Installing dependencies...
01:16:55.951 | ▲  up to date in 2s
01:16:55.952 | ▲  243 packages are looking for funding
01:16:55.953 | ▲  run `npm fund` for details
01:16:55.967 | ▲  Detected Next.js version: 14.1.0
01:16:55.976 | ▲  Detected `package-lock.json` generated by npm 7+
01:16:55.977 | ▲  Running "npm run build"
01:16:56.362 | ▲  > streamdefi-dashboard@0.1.0 build
01:16:56.362 | ▲  > next build
01:16:57.013 | ▲  Attention: Next.js now collects completely anonymous telemetry regarding usage.
01:16:57.013 | ▲  This information is used to shape Next.js' roadmap and prioritize features.
01:16:57.014 | ▲  You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
01:16:57.014 | ▲  https://nextjs.org/telemetry
01:16:57.014 | ▲
01:16:57.123 | ▲  ▲ Next.js 14.1.0
01:16:57.124 | ▲
01:16:57.187 | ▲  Creating an optimized production build ...
01:17:54.339 | ▲  ✓ Compiled successfully
01:17:54.340 | ▲  Linting and checking validity of types ...
01:17:56.873 | ▲  ./src/app/components/ManageVault/RollToNextRound.tsx
01:17:56.873 | ▲  116:6  Warning: React Hook useEffect has a missing dependency: 'assetContract'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
01:17:56.874 | ▲
01:17:56.874 | ▲  info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
01:18:00.344 | ▲  Collecting page data ...
01:18:01.722 | ▲  Error: Project ID is not defined
01:18:01.723 | ▲  at 75734 (/opt/buildhome/repo/.next/server/app/_not-found.js:1610:120919)
01:18:01.723 | ▲  at __webpack_require__ (/opt/buildhome/repo/.next/server/edge-runtime-webpack.js:25:43)
01:18:01.724 | ▲  at 66231 (/opt/buildhome/repo/.next/server/app/_not-found.js:1564:147773)
01:18:01.724 | ▲  at Function.__webpack_require__ (/opt/buildhome/repo/.next/server/edge-runtime-webpack.js:25:43)
01:18:01.725 | ▲  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
01:18:01.726 | ▲  > Build error occurred
01:18:01.729 | ▲  Error: Failed to collect page data for /_not-found
01:18:01.729 | ▲    at /opt/buildhome/repo/node_modules/next/dist/build/utils.js:1258:15
01:18:01.729 | ▲    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
01:18:01.729 | ▲  type: 'Error'
01:18:01.729 | ▲  }
01:18:01.811 | ▲  Error: Command "npm run build" exited with 1
01:18:01.895 |  
01:18:01.895 | ⚡️ The Vercel build (`npx vercel build`) command failed. For more details see the Vercel logs above.
01:18:01.895 | ⚡️ If you need help solving the issue, refer to the Vercel or Next.js documentation or their repositories.
01:18:01.896 |  
01:18:01.914 | Failed: Error while executing user command. Exited with error code: 1
01:18:01.923 | Failed: build command exited with code: 1
01:18:02.886 | Failed: error occurred while running build command

### Description

Building locally is fine, however when I push and Pages builds on Cloudflare, I run into the above error.

### Pages Deployment Method

Pages CI (GitHub/GitLab integration)

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment]
Hi @Oni-giri 🙂, thanks for the issue, could you share your deployment ID? 🙏 

<details>
<summary>How to get the deployment ID</summary>

To find the deployment id, in the Cloudflare dashboard go to your project's deployment details page and the id will be the second hash in the page's URL 

The URL being: `https://dash.cloudflare.com/<ACCOUNT_ID>/pages/view/<PROJECT_NAME>/<DEPLOYMENT_ID>`

</details>

**Comment by dario-piotrowicz** [comment]
Hello 🙂

Earlier this year we released our [Cloudflare adapter for OpenNext](https://opennext.js.org/cloudflare), and we have been continuously investing effort in its improvement since then. Existing deployments can continue to use the next-on-pages tooling, but the Cloudflare adapter for OpenNext is currently stable and recommended for deployment of Next.js applications to Cloudflare.

As such, we will no longer be maintaining next-on-pages. We recently deprecated the package on npm and we plan to archive this repo on Monday Sep 29, 2025. In preparation for archival, we are closing all open issues and PRs.

If you have concerns, please feel free to reply here before the repo is archived (after that, it will no longer be possible to comment) or to reach out to our team on [Discord](https://discord.com/invite/cloudflaredev).

Thanks so much for using and contributing to next-on-pages 🧡
