### ISSUE TITLE
Unable to generate a build

### ISSUE THREAD

**Issue by codeoholic** [cloudflare/next-on-pages#7]
Build fails with this error.
<pre class="c_jh c_bq c_ii c_ij c_rw c_my c_da c_ju c_qe c_qc c_qd c_ft c_fu c_rx c_bs c_so">

14:45:21.962 | Executing user command: npx @cloudflare/next-on-pages --experimental-minify
-- | --
14:45:22.140 | /opt/buildhome/repo/node_modules/@cloudflare/next-on-pages/dist/index.js:6013
14:45:22.140 | ({ type, expression }) => type === "ExpressionStatement" && expression?.type === "CallExpression" && expression.callee?.type === "MemberExpression" && expression.callee.object?.type === "AssignmentExpression" && expression.callee.object.left?.object?.name === "self" && expression.callee.object.left.property?.value === "webpackChunk_N_E" && expression.arguments?.[0]?.elements?.[1]?.type === "ObjectExpression"
14:45:22.141 | ^
14:45:22.141 |  
14:45:22.141 | SyntaxError: Unexpected token '.'
14:45:22.141 | at wrapSafe (internal/modules/cjs/loader.js:1054:16)
14:45:22.142 | at Module._compile (internal/modules/cjs/loader.js:1102:27)
14:45:22.142 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
14:45:22.142 | at Module.load (internal/modules/cjs/loader.js:986:32)
14:45:22.142 | at Function.Module._load (internal/modules/cjs/loader.js:879:14)
14:45:22.142 | at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
14:45:22.142 | at internal/main/run_main_module.js:17:47
14:45:22.152 | Failed: build command exited with code: 1
14:45:23.193 | Failed: an internal error occurred

</pre>

@cloudflare/next-on-pages - ^0.1.0
vercel - ^28.4.12

**Comment by codeoholic** [comment]
False alarm. I missed adding the NODE_VERSION and it worked like a charm after that.
