### ISSUE TITLE
SyntaxError: Unexpected token '.' at wrapSafe (internal/modules/cjs/loader.js:1054:16)

### ISSUE THREAD

**Issue by negrusti** [cloudflare/next-on-pages#81]
Getting this at the start of the build with Next.js preset:
```
02:06:05.733	Executing user command: npx @cloudflare/next-on-pages --experimental-minify
02:06:11.212	/opt/buildhome/.npm/_npx/1494/lib/node_modules/@cloudflare/next-on-pages/dist/index.js:6013
02:06:11.213	              ({ type, expression }) => type === "ExpressionStatement" && expression?.type === "CallExpression" && expression.callee?.type === "MemberExpression" && expression.callee.object?.type === "AssignmentExpression" && expression.callee.object.left?.object?.name === "self" && expression.callee.object.left.property?.value === "webpackChunk_N_E" && expression.arguments?.[0]?.elements?.[1]?.type === "ObjectExpression"
02:06:11.213	                                                                                     ^
02:06:11.213	
02:06:11.213	SyntaxError: Unexpected token '.'
02:06:11.213	    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
02:06:11.213	    at Module._compile (internal/modules/cjs/loader.js:1102:27)
02:06:11.214	    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
02:06:11.214	    at Module.load (internal/modules/cjs/loader.js:986:32)
02:06:11.214	    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
02:06:11.214	    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
02:06:11.214	    at internal/main/run_main_module.js:17:47
02:06:11.277	Failed: build command exited with code: 1
02:06:12.327	Failed: an internal error occurred
```

**Comment by WalshyDev** [comment]
You need to set a `NODE_VERSION` environment variable with a version of `14` or higher. Step 7 in the README.
