### ISSUE TITLE
Next.js 13

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/next-on-pages#9]

**Comment by hyunjunian** [comment]
With next.js 13, cloudflare deploy failed!

```
00:00:42.007 | ⚡️ Completed 'npx vercel build'.
-- | --
00:00:42.007 | ⚡️
00:00:42.151 | /opt/buildhome/.npm/_npx/39e2fd552b408994/node_modules/@cloudflare/next-on-pages/dist/index.js:3057
00:00:42.151 | var err = new SyntaxError(message);
00:00:42.151 | ^
00:00:42.151 |  
00:00:42.151 | SyntaxError: Identifier 'n' has already been declared (232:9646)
00:00:42.152 | at Parser2.pp$4.raise (/opt/buildhome/.npm/_npx/39e2fd552b408994/node_modules/@cloudflare/next-on-pages/dist/index.js:3057:13)
00:00:42.152 | at Parser2.pp$3.declareName (/opt/buildhome/.npm/_npx/39e2fd552b408994/node_modules/@cloudflare/next-on-pages/dist/index.js:3123:10)
00:00:42.152 | at Parser2.pp$7.checkLValSimple (/opt/buildhome/.npm/_npx/39e2fd552b408994/node_modules/@cloudflare/next-on-pages/dist/index.js:1858:16)
00:00:42.152 | at Parser2.pp$7.checkLValPattern (/opt/buildhome/.npm/_npx/39e2fd552b408994/node_modules/@cloudflare/next-on-pages/dist/index.js:1898:12)
00:00:42.153 | at Parser2.pp$8.parseVarId (/opt/buildhome/.npm/_npx/39e2fd552b408994/node_modules/@cloudflare/next-on-pages/dist/index.js:1193:8)
00:00:42.154 | at Parser2.pp$8.parseVar (/opt/buildhome/.npm/_npx/39e2fd552b408994/node_modules/@cloudflare/next-on-pages/dist/index.js:1174:10)
00:00:42.154 | at Parser2.pp$8.parseVarStatement (/opt/buildhome/.npm/_npx/39e2fd552b408994/node_modules/@cloudflare/next-on-pages/dist/index.js:1064:8)
00:00:42.154 | at Parser2.pp$8.parseStatement (/opt/buildhome/.npm/_npx/39e2fd552b408994/node_modules/@cloudflare/next-on-pages/dist/index.js:803:19)
00:00:42.154 | at Parser2.pp$8.parseBlock (/opt/buildhome/.npm/_npx/39e2fd552b408994/node_modules/@cloudflare/next-on-pages/dist/index.js:1128:21)
00:00:42.154 | at Parser2.pp$5.parseFunctionBody (/opt/buildhome/.npm/_npx/39e2fd552b408994/node_modules/@cloudflare/next-on-pages/dist/index.js:2912:22) {
00:00:42.154 | pos: 77735,
00:00:42.155 | loc: Position2 { line: 232, column: 9646 },
00:00:42.155 | raisedAt: 77737
00:00:42.155 | }
```

**Comment by diptnc** [comment]
getting a similar error. 

```
2022-11-01T09:32:06.063433Z	Cloning repository...
2022-11-01T09:32:07.278642Z	From https://github.com/diptnc/nextjsexperimentalapp
2022-11-01T09:32:07.279296Z	 * branch            2b9a7239bec4e649faa6daea2b64d6eed2e0fd1e -> FETCH_HEAD
2022-11-01T09:32:07.279489Z	
2022-11-01T09:32:07.316867Z	HEAD is now at 2b9a723 depoertldfl
2022-11-01T09:32:07.317430Z	
2022-11-01T09:32:07.454284Z	
2022-11-01T09:32:07.480775Z	Success: Finished cloning repository files
2022-11-01T09:32:08.074441Z	Installing dependencies
2022-11-01T09:32:08.086501Z	Python version set to 2.7
2022-11-01T09:32:11.338804Z	Downloading and installing node v16.8.0...
2022-11-01T09:32:11.775397Z	Downloading https://nodejs.org/dist/v16.8.0/node-v16.8.0-linux-x64.tar.xz...
2022-11-01T09:32:12.203172Z	Computing checksum with sha256sum
2022-11-01T09:32:12.330493Z	Checksums matched!
2022-11-01T09:32:16.523007Z	Now using node v16.8.0 (npm v7.21.0)
2022-11-01T09:32:16.926127Z	Started restoring cached build plugins
2022-11-01T09:32:16.939344Z	Finished restoring cached build plugins
2022-11-01T09:32:17.456580Z	Attempting ruby version 2.7.1, read from environment
2022-11-01T09:32:20.994815Z	Using ruby version 2.7.1
2022-11-01T09:32:21.343149Z	Using PHP version 5.6
2022-11-01T09:32:21.500877Z	5.2 is already installed.
2022-11-01T09:32:21.527268Z	Using Swift version 5.2
2022-11-01T09:32:21.527977Z	Started restoring cached node modules
2022-11-01T09:32:21.543516Z	Finished restoring cached node modules
2022-11-01T09:32:21.966850Z	Installing NPM modules using NPM version 7.21.0
2022-11-01T09:32:28.188683Z	
2022-11-01T09:32:28.188990Z	added 19 packages, and audited 20 packages in 6s
2022-11-01T09:32:28.189159Z	
2022-11-01T09:32:28.189302Z	2 packages are looking for funding
2022-11-01T09:32:28.189417Z	  run `npm fund` for details
2022-11-01T09:32:28.190198Z	
2022-11-01T09:32:28.190383Z	found 0 vulnerabilities
2022-11-01T09:32:28.201728Z	NPM modules installed
2022-11-01T09:32:28.705517Z	Installing Hugo 0.54.0
2022-11-01T09:32:39.442737Z	Hugo Static Site Generator v0.54.0-B1A82C61A/extended linux/amd64 BuildDate: 2019-02-01T10:04:38Z
2022-11-01T09:32:39.447185Z	Started restoring cached go cache
2022-11-01T09:32:39.465494Z	Finished restoring cached go cache
2022-11-01T09:32:39.611124Z	go version go1.14.4 linux/amd64
2022-11-01T09:32:39.627167Z	go version go1.14.4 linux/amd64
2022-11-01T09:32:39.630166Z	Installing missing commands
2022-11-01T09:32:39.630424Z	Verify run directory
2022-11-01T09:32:39.630561Z	Executing user command: npx @cloudflare/next-on-pages --experimental-minify
2022-11-01T09:32:40.459298Z	npm WARN exec The following package was not found and will be installed: @cloudflare/next-on-pages
2022-11-01T09:32:48.960089Z	⚡️ @cloudflare/next-to-pages CLI
2022-11-01T09:32:48.964282Z	⚡️
2022-11-01T09:32:48.964557Z	⚡️ Installing 'vercel' CLI...
2022-11-01T09:32:48.964698Z	⚡️
2022-11-01T09:32:53.175108Z	▲ 
2022-11-01T09:32:53.175435Z	▲ added 213 packages, and audited 233 packages in 4s
2022-11-01T09:32:53.175606Z	▲ 
2022-11-01T09:32:53.175761Z	▲ 
2022-11-01T09:32:53.175918Z	▲ 29 packages are looking for funding
2022-11-01T09:32:53.176046Z	▲   run `npm fund` for details
2022-11-01T09:32:53.176176Z	▲ 
2022-11-01T09:32:53.188499Z	▲ 
2022-11-01T09:32:53.188734Z	▲ 5 moderate severity vulnerabilities
2022-11-01T09:32:53.188869Z	▲ 
2022-11-01T09:32:53.189000Z	▲ To address all issues, run:
2022-11-01T09:32:53.189114Z	▲   npm audit fix
2022-11-01T09:32:53.189260Z	▲ 
2022-11-01T09:32:53.189384Z	▲ Run `npm audit` for details.
2022-11-01T09:32:53.189495Z	▲ 
2022-11-01T09:32:53.200081Z	⚡️
2022-11-01T09:32:53.200324Z	⚡️
2022-11-01T09:32:53.200482Z	⚡️ Completed 'npx vercel build'.
2022-11-01T09:32:53.200625Z	⚡️
2022-11-01T09:32:53.200743Z	⚡️
2022-11-01T09:32:53.200856Z	⚡️ Building project with 'npx vercel build'...
2022-11-01T09:32:53.201005Z	⚡️
2022-11-01T09:32:54.333481Z	▲ Vercel CLI 28.4.12
2022-11-01T09:32:54.333854Z	▲ 
2022-11-01T09:32:54.695141Z	▲ Installing dependencies...
2022-11-01T09:32:54.695469Z	▲ 
2022-11-01T09:32:55.513652Z	▲ 
2022-11-01T09:32:55.513969Z	▲ up to date in 644ms
2022-11-01T09:32:55.514128Z	▲ 
2022-11-01T09:32:55.514287Z	▲ 
2022-11-01T09:32:55.514418Z	▲ 
2022-11-01T09:32:55.514585Z	▲ 29 packages are looking for funding
2022-11-01T09:32:55.514704Z	▲   run `npm fund` for details
2022-11-01T09:32:55.514815Z	▲ 
2022-11-01T09:32:55.523798Z	▲ Detected Next.js version: 13.0.1
2022-11-01T09:32:55.524163Z	▲ 
2022-11-01T09:32:55.529744Z	▲ Detected `package-lock.json` generated by npm 7+...
2022-11-01T09:32:55.530087Z	▲ 
2022-11-01T09:32:55.530379Z	▲ Running "npm run build"
2022-11-01T09:32:55.530619Z	▲ 
2022-11-01T09:32:55.881319Z	▲ 
2022-11-01T09:32:55.881630Z	▲ > nextjsexperimentalapp@0.1.0 build
2022-11-01T09:32:55.881786Z	▲ > next build
2022-11-01T09:32:55.881928Z	▲ 
2022-11-01T09:32:55.882050Z	▲ 
2022-11-01T09:32:56.435542Z	▲ warn  - You have enabled experimental features (appDir, runtime) in next.config.js.
2022-11-01T09:32:56.435878Z	▲ 
2022-11-01T09:32:56.436086Z	▲ warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
2022-11-01T09:32:56.436271Z	▲ 
2022-11-01T09:32:56.436397Z	▲ 
2022-11-01T09:32:56.436518Z	▲ 
2022-11-01T09:32:56.436631Z	▲ info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback
2022-11-01T09:32:56.436744Z	▲ 
2022-11-01T09:32:56.494174Z	▲ Attention: Next.js now collects completely anonymous telemetry regarding usage.
2022-11-01T09:32:56.494626Z	▲ This information is used to shape Next.js' roadmap and prioritize features.
2022-11-01T09:32:56.494900Z	▲ 
2022-11-01T09:32:56.495162Z	▲ You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
2022-11-01T09:32:56.495316Z	▲ https://nextjs.org/telemetry
2022-11-01T09:32:56.495569Z	▲ 
2022-11-01T09:32:56.495791Z	▲ 
2022-11-01T09:32:56.624454Z	▲ info  - Creating an optimized production build...
2022-11-01T09:32:56.624957Z	▲ 
2022-11-01T09:32:56.671820Z	▲ warn  - You are using the experimental Edge Runtime with `experimental.runtime`.
2022-11-01T09:32:56.672074Z	▲ 
2022-11-01T09:33:03.527617Z	▲ info  - Compiled successfully
2022-11-01T09:33:03.527951Z	▲ 
2022-11-01T09:33:03.528108Z	▲ info  - Linting and checking validity of types...
2022-11-01T09:33:03.528246Z	▲ 
2022-11-01T09:33:03.947550Z	▲ info  - Collecting page data...
2022-11-01T09:33:03.947828Z	▲ 
2022-11-01T09:33:08.882544Z	▲ info  - Generating static pages (0/2)
2022-11-01T09:33:08.882834Z	▲ 
2022-11-01T09:33:08.967246Z	▲ info  - Generating static pages (2/2)
2022-11-01T09:33:08.967513Z	▲ 
2022-11-01T09:33:08.982311Z	▲ info  - Finalizing page optimization...
2022-11-01T09:33:08.982732Z	▲ 
2022-11-01T09:33:08.986218Z	▲ 
2022-11-01T09:33:08.986429Z	▲ 
2022-11-01T09:33:09.005038Z	▲ Route (app)                                Size     First Load JS
2022-11-01T09:33:09.005238Z	▲ ─ ℇ /                                      0 B                0 B
2022-11-01T09:33:09.005384Z	▲ + First Load JS shared by all              64.2 kB
2022-11-01T09:33:09.005503Z	▲   ├ chunks/17-521a5439222a82c0.js          62 kB
2022-11-01T09:33:09.005616Z	▲   ├ chunks/main-app-c5031435e4d1ed94.js    200 B
2022-11-01T09:33:09.005727Z	▲   └ chunks/webpack-9e765e27c32b1a64.js     2.07 kB
2022-11-01T09:33:09.005869Z	▲ 
2022-11-01T09:33:09.006024Z	▲ Route (pages)                              Size     First Load JS
2022-11-01T09:33:09.006155Z	▲ ┌ ○ /404                                   179 B          79.8 kB
2022-11-01T09:33:09.006274Z	▲ └ ℇ /api/hello                             0 B            79.6 kB
2022-11-01T09:33:09.006388Z	▲ + First Load JS shared by all              79.6 kB
2022-11-01T09:33:09.006513Z	▲   ├ chunks/main-89022d600e76ddf0.js        77.4 kB
2022-11-01T09:33:09.006628Z	▲   ├ chunks/pages/_app-9f5490aa3d56632f.js  192 B
2022-11-01T09:33:09.006745Z	▲   └ chunks/webpack-9e765e27c32b1a64.js     2.07 kB
2022-11-01T09:33:09.006901Z	▲ 
2022-11-01T09:33:09.007058Z	▲ 
2022-11-01T09:33:09.007179Z	▲ ℇ  (Streaming)  server-side renders with streaming (uses React 18 SSR streaming or Server Components)
2022-11-01T09:33:09.007304Z	▲ ○  (Static)     automatically rendered as static HTML (uses no initial props)
2022-11-01T09:33:09.007421Z	▲ 
2022-11-01T09:33:09.007534Z	▲ 
2022-11-01T09:33:10.382530Z	▲ Traced Next.js server files in: 1.227s
2022-11-01T09:33:10.383009Z	▲ 
2022-11-01T09:33:11.045775Z	▲ Created all serverless functions in: 662.849ms
2022-11-01T09:33:11.046105Z	▲ 
2022-11-01T09:33:11.190877Z	▲ Collected static files (public/, static/, .next/static): 5.586ms
2022-11-01T09:33:11.191304Z	▲ 
2022-11-01T09:33:11.234335Z	▲ Build Completed in .vercel/output [17s]
2022-11-01T09:33:11.234614Z	▲ 
2022-11-01T09:33:11.300015Z	⚡️
2022-11-01T09:33:11.300304Z	⚡️
2022-11-01T09:33:11.300488Z	⚡️ Completed 'npx vercel build'.
2022-11-01T09:33:11.300668Z	⚡️
2022-11-01T09:33:11.445166Z	/opt/buildhome/.npm/_npx/39e2fd552b408994/node_modules/@cloudflare/next-on-pages/dist/index.js:3057
2022-11-01T09:33:11.445484Z	  var err = new SyntaxError(message);
2022-11-01T09:33:11.445643Z	            ^
2022-11-01T09:33:11.445816Z	
2022-11-01T09:33:11.445985Z	SyntaxError: Identifier 'n' has already been declared (232:9643)
2022-11-01T09:33:11.446119Z	    at Parser2.pp$4.raise (/opt/buildhome/.npm/_npx/39e2fd552b408994/node_modules/@cloudflare/next-on-pages/dist/index.js:3057:13)
2022-11-01T09:33:11.446271Z	    at Parser2.pp$3.declareName (/opt/buildhome/.npm/_npx/39e2fd552b408994/node_modules/@cloudflare/next-on-pages/dist/index.js:3123:10)
2022-11-01T09:33:11.446417Z	    at Parser2.pp$7.checkLValSimple (/opt/buildhome/.npm/_npx/39e2fd552b408994/node_modules/@cloudflare/next-on-pages/dist/index.js:1858:16)
2022-11-01T09:33:11.446555Z	    at Parser2.pp$7.checkLValPattern (/opt/buildhome/.npm/_npx/39e2fd552b408994/node_modules/@cloudflare/next-on-pages/dist/index.js:1898:12)
2022-11-01T09:33:11.446707Z	    at Parser2.pp$8.parseVarId (/opt/buildhome/.npm/_npx/39e2fd552b408994/node_modules/@cloudflare/next-on-pages/dist/index.js:1193:8)
2022-11-01T09:33:11.446874Z	    at Parser2.pp$8.parseVar (/opt/buildhome/.npm/_npx/39e2fd552b408994/node_modules/@cloudflare/next-on-pages/dist/index.js:1174:10)
2022-11-01T09:33:11.447035Z	    at Parser2.pp$8.parseVarStatement (/opt/buildhome/.npm/_npx/39e2fd552b408994/node_modules/@cloudflare/next-on-pages/dist/index.js:1064:8)
2022-11-01T09:33:11.447189Z	    at Parser2.pp$8.parseStatement (/opt/buildhome/.npm/_npx/39e2fd552b408994/node_modules/@cloudflare/next-on-pages/dist/index.js:803:19)
2022-11-01T09:33:11.447362Z	    at Parser2.pp$8.parseBlock (/opt/buildhome/.npm/_npx/39e2fd552b408994/node_modules/@cloudflare/next-on-pages/dist/index.js:1128:21)
2022-11-01T09:33:11.447515Z	    at Parser2.pp$5.parseFunctionBody (/opt/buildhome/.npm/_npx/39e2fd552b408994/node_modules/@cloudflare/next-on-pages/dist/index.js:2912:22) {
2022-11-01T09:33:11.447667Z	  pos: 77838,
2022-11-01T09:33:11.447800Z	  loc: Position2 { line: 232, column: 9643 },
2022-11-01T09:33:11.447965Z	  raisedAt: 77840
2022-11-01T09:33:11.448130Z	}
2022-11-01T09:33:11.468275Z	Failed: build command exited with code: 1
```

**Comment by charlescarrasco** [comment]
## Run Next.js 13 (static websites only)
If you are looking to run Next.js 13.0.1 statically without the edge runtime or any server functions, it can be done using the new Next.js (Not Next.js Static HTML Export). The Static HTML Export does not work for version 13 or its new app directory. When using the new Next.js option in Cloudflare Pages, do not add the Edge Runtime option, it will not work. Next.js 13 requires a minimum Node version of 14 and requires 16 when using the app directory.

**Comment by debanjanbasu** [comment]
> ## Run Next.js 13 (static websites only)
> If you are looking to run Next.js 13.0.1 statically without the edge runtime or any server functions, it can be done using the new Next.js (Not Next.js Static HTML Export). The Static HTML Export does not work for version 13 or its new app directory. When using the new Next.js option in Cloudflare Pages, do not add the Edge Runtime option, it will not work. Next.js 13 requires a minimum Node version of 14 and requires 16 when using the app directory.

This does not explain, why the edge-runtime wouldn't be working. Are you saying that only Static Sites are supported for NextJS 13.0.1 ?

**Comment by charlescarrasco** [comment]
> > ## Run Next.js 13 (static websites only)
> 
> > If you are looking to run Next.js 13.0.1 statically without the edge runtime or any server functions, it can be done using the new Next.js (Not Next.js Static HTML Export). The Static HTML Export does not work for version 13 or its new app directory. When using the new Next.js option in Cloudflare Pages, do not add the Edge Runtime option, it will not work. Next.js 13 requires a minimum Node version of 14 and requires 16 when using the app directory.
> 
> 
> 
> This does not explain, why the edge-runtime wouldn't be working. Are you saying that only Static Sites are supported for NextJS 13.0.1 ?

Currently version 12 is only supported by this, and the only way I got version 13 to work was to deploy 13 statically using the cloudflare-on-pages (the new Next.js option in pages) module. There may be a potential fix for edge runtime in pull requests, until then, I'm saying static sites on 13 are fully supported using this module.

**Comment by msdrigg** [comment]
Would love this to include support for the new app directory—thats the main reason I would want to upgrade to next 13

**Comment by speier** [comment]
Is there any update regarding Next.js 13 support? Vercel just deployed 13.0.3.. 🙏

**Comment by cloudcreatr** [comment]
How do you know vercel has deployed it

**Comment by speier** [comment]
Sorry I meant they released it: https://github.com/vercel/next.js/releases/tag/v13.0.3

**Comment by PanosJee** [comment]
It is stated that `cache` will not ever be supported, which essentially will make the transition to `13` worthless, given how central this is for NextJS going forward. Pretty much without respecting `cache` we won't be able to do static exports anymore.

Are you planning to provide a fetch replacement that uses `KV` underneath and will be compatible with the 13 principles? It seems to be that building blocks are there already.

**Comment by cmj2002** [comment]
I solved it by adding environment variable `NODE_VERSION` = `16.18.0`. Any version larger than 14.x should work.

**Comment by xyba1337** [comment]
> I solved it by adding environment variable `NODE_VERSION` = `16.18.0`. Any version larger than 14.x should work.

You just saved me from hours of research, god bless you

**Comment by emrecoban** [comment]
Don't forget to follow this page: https://developers.cloudflare.com/pages/framework-guides/deploy-a-nextjs-site/

I solved this issue: Workers & Pages > Select your project > Settings on tab > Build & deployments > Build system version > Configure build system. You will see node.js version, select you need.
